"""baseline

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-09-20 13:55:13.667419

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('chat_exchange_feedback',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('exchange_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), server_default='default', nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False, comment='1=thumbs_up, -1=thumbs_down'),
    sa.Column('comment', sa.Text(), nullable=True, comment='可选评论文本'),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_exchange_feedback_conversation_id'), 'chat_exchange_feedback', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_exchange_feedback_exchange_id'), 'chat_exchange_feedback', ['exchange_id'], unique=False)
    op.create_table('chat_model_usage_trace',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('exchange_id', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('stage_code', sa.String(length=64), nullable=True),
    sa.Column('usage_type', sa.String(length=32), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_model_usage_trace_exchange_id'), 'chat_model_usage_trace', ['exchange_id'], unique=False)
    op.create_index(op.f('ix_chat_model_usage_trace_session_id'), 'chat_model_usage_trace', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_model_usage_trace_trace_id'), 'chat_model_usage_trace', ['trace_id'], unique=False)
    op.create_table('conversation_rag_evaluation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('exchange_id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('faithfulness_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('answer_relevancy_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('context_precision_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('eval_status', sa.String(length=20), nullable=False),
    sa.Column('eval_message', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_rag_evaluation_conversation_id'), 'conversation_rag_evaluation', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_rag_evaluation_exchange_id'), 'conversation_rag_evaluation', ['exchange_id'], unique=False)
    op.create_table('conversation_session',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), server_default='default', nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('chat_mode', sa.String(length=32), nullable=False),
    sa.Column('memory_strategy', sa.String(length=32), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('pinned_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    op.create_index(op.f('ix_conversation_session_tenant_id'), 'conversation_session', ['tenant_id'], unique=False)
    op.create_table('feishu_binding',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.String(length=64), nullable=False),
    sa.Column('open_id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'open_id', name='uk_feishu_binding_chat_open')
    )
    op.create_index(op.f('ix_feishu_binding_chat_id'), 'feishu_binding', ['chat_id'], unique=False)
    op.create_index(op.f('ix_feishu_binding_conversation_id'), 'feishu_binding', ['conversation_id'], unique=False)
    op.create_table('pipeline_rag_chat_channel_execution',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dialogue_code', sa.String(length=64), nullable=False),
    sa.Column('exchange_id', sa.BigInteger(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('sub_question_index', sa.Integer(), nullable=False),
    sa.Column('sub_question', sa.Text(), nullable=False),
    sa.Column('channel_type', sa.String(length=32), nullable=False),
    sa.Column('execution_state', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('recalled_count', sa.Integer(), nullable=False),
    sa.Column('accepted_count', sa.Integer(), nullable=False),
    sa.Column('final_selected_count', sa.Integer(), nullable=False),
    sa.Column('avg_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('max_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('min_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('config_snapshot', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_rag_chat_channel_execution_dialogue_code'), 'pipeline_rag_chat_channel_execution', ['dialogue_code'], unique=False)
    op.create_index(op.f('ix_pipeline_rag_chat_channel_execution_exchange_id'), 'pipeline_rag_chat_channel_execution', ['exchange_id'], unique=False)
    op.create_table('pipeline_rag_chat_dialogue',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dialogue_code', sa.String(length=64), nullable=False),
    sa.Column('dialogue_stage', sa.Integer(), nullable=True),
    sa.Column('chat_mode', sa.Integer(), nullable=True),
    sa.Column('selected_document_id', sa.BigInteger(), nullable=True),
    sa.Column('selected_document_name', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_rag_chat_dialogue_dialogue_code'), 'pipeline_rag_chat_dialogue', ['dialogue_code'], unique=False)
    op.create_table('pipeline_rag_chat_exchange',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dialogue_code', sa.String(length=64), nullable=False),
    sa.Column('user_prompt', sa.Text(), nullable=False),
    sa.Column('reply_content', sa.Text(), nullable=True),
    sa.Column('reasoning_note_list', sa.Text(), nullable=True),
    sa.Column('source_snapshot_list', sa.Text(), nullable=True),
    sa.Column('followup_suggestion_list', sa.Text(), nullable=True),
    sa.Column('tool_trace_list', sa.Text(), nullable=True),
    sa.Column('debug_trace_json', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.BigInteger(), nullable=True),
    sa.Column('execution_mode', sa.String(length=32), nullable=True),
    sa.Column('exchange_state', sa.Integer(), nullable=True),
    sa.Column('finish_note', sa.Text(), nullable=True),
    sa.Column('first_token_latency_ms', sa.BigInteger(), nullable=True),
    sa.Column('total_latency_ms', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_rag_chat_exchange_dialogue_code'), 'pipeline_rag_chat_exchange', ['dialogue_code'], unique=False)
    op.create_table('pipeline_rag_chat_exchange_trace_stage',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dialogue_code', sa.String(length=64), nullable=False),
    sa.Column('exchange_id', sa.BigInteger(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('stage_code', sa.String(length=64), nullable=False),
    sa.Column('stage_name', sa.String(length=256), nullable=True),
    sa.Column('stage_order', sa.Integer(), nullable=True),
    sa.Column('stage_level', sa.Integer(), nullable=True),
    sa.Column('parent_stage_id', sa.BigInteger(), nullable=True),
    sa.Column('execution_mode', sa.String(length=32), nullable=True),
    sa.Column('stage_state', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('snapshot_json', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_rag_chat_exchange_trace_stage_dialogue_code'), 'pipeline_rag_chat_exchange_trace_stage', ['dialogue_code'], unique=False)
    op.create_index(op.f('ix_pipeline_rag_chat_exchange_trace_stage_exchange_id'), 'pipeline_rag_chat_exchange_trace_stage', ['exchange_id'], unique=False)
    op.create_table('pipeline_rag_chat_memory_summary',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dialogue_code', sa.String(length=64), nullable=False),
    sa.Column('covered_exchange_id', sa.BigInteger(), nullable=True),
    sa.Column('covered_exchange_count', sa.Integer(), nullable=True),
    sa.Column('compression_count', sa.Integer(), nullable=True),
    sa.Column('summary_version', sa.Integer(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('summary_json', sa.Text(), nullable=True),
    sa.Column('last_source_edit_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_rag_chat_memory_summary_dialogue_code'), 'pipeline_rag_chat_memory_summary', ['dialogue_code'], unique=False)
    op.create_table('pipeline_rag_chat_retrieval_result',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dialogue_code', sa.String(length=64), nullable=False),
    sa.Column('exchange_id', sa.BigInteger(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('sub_question_index', sa.Integer(), nullable=True),
    sa.Column('sub_question', sa.Text(), nullable=False),
    sa.Column('channel_type', sa.String(length=32), nullable=True),
    sa.Column('channel_rank', sa.Integer(), nullable=True),
    sa.Column('rrf_rank', sa.Integer(), nullable=True),
    sa.Column('final_rank', sa.Integer(), nullable=True),
    sa.Column('original_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rrf_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rerank_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('gate_passed', sa.Integer(), nullable=True),
    sa.Column('is_elevated', sa.Integer(), nullable=True),
    sa.Column('is_selected', sa.Integer(), nullable=True),
    sa.Column('selection_reason', sa.Text(), nullable=True),
    sa.Column('document_id', sa.BigInteger(), nullable=True),
    sa.Column('document_name', sa.String(length=256), nullable=True),
    sa.Column('chunk_id', sa.BigInteger(), nullable=True),
    sa.Column('chunk_no', sa.Integer(), nullable=True),
    sa.Column('parent_block_id', sa.BigInteger(), nullable=True),
    sa.Column('parent_block_no', sa.Integer(), nullable=True),
    sa.Column('section_path', sa.Text(), nullable=True),
    sa.Column('chunk_text_preview', sa.Text(), nullable=True),
    sa.Column('chunk_char_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_rag_chat_retrieval_result_dialogue_code'), 'pipeline_rag_chat_retrieval_result', ['dialogue_code'], unique=False)
    op.create_index(op.f('ix_pipeline_rag_chat_retrieval_result_exchange_id'), 'pipeline_rag_chat_retrieval_result', ['exchange_id'], unique=False)
    op.create_table('pipeline_rag_document',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), server_default='default', nullable=False),
    sa.Column('doc_id', sa.String(length=64), nullable=False),
    sa.Column('document_name', sa.String(length=256), nullable=False),
    sa.Column('original_file_name', sa.String(length=256), nullable=False),
    sa.Column('file_type', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('storage_type', sa.Integer(), nullable=True),
    sa.Column('bucket_name', sa.String(length=128), nullable=True),
    sa.Column('object_name', sa.String(length=256), nullable=True),
    sa.Column('object_url', sa.String(length=512), nullable=True),
    sa.Column('parse_status', sa.Integer(), nullable=False),
    sa.Column('strategy_status', sa.Integer(), nullable=True),
    sa.Column('index_status', sa.Integer(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('structure_level', sa.Integer(), nullable=True),
    sa.Column('content_quality_level', sa.Integer(), nullable=True),
    sa.Column('parse_text_path', sa.String(length=512), nullable=True),
    sa.Column('parse_error_msg', sa.Text(), nullable=True),
    sa.Column('knowledge_scope_code', sa.String(length=64), nullable=True),
    sa.Column('knowledge_scope_name', sa.String(length=128), nullable=True),
    sa.Column('business_category', sa.String(length=128), nullable=True),
    sa.Column('document_tags', sa.String(length=512), nullable=True),
    sa.Column('current_plan_id', sa.BigInteger(), nullable=True),
    sa.Column('last_parse_task_id', sa.String(length=128), nullable=True),
    sa.Column('last_index_task_id', sa.String(length=128), nullable=True),
    sa.Column('structure_node_count', sa.Integer(), nullable=True),
    sa.Column('pipeline_stage', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_id')
    )
    op.create_index(op.f('ix_pipeline_rag_document_tenant_id'), 'pipeline_rag_document', ['tenant_id'], unique=False)
    op.create_table('pipeline_rag_document_parent_block',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.String(length=128), nullable=True),
    sa.Column('plan_id', sa.BigInteger(), nullable=True),
    sa.Column('parent_no', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.Integer(), nullable=True),
    sa.Column('section_path', sa.Text(), nullable=True),
    sa.Column('structure_node_id', sa.BigInteger(), nullable=True),
    sa.Column('structure_node_type', sa.Integer(), nullable=True),
    sa.Column('canonical_path', sa.Text(), nullable=True),
    sa.Column('item_index', sa.Integer(), nullable=True),
    sa.Column('parent_text', sa.Text(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('child_count', sa.Integer(), nullable=True),
    sa.Column('start_chunk_no', sa.Integer(), nullable=True),
    sa.Column('end_chunk_no', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_rag_document_strategy_plan',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=True),
    sa.Column('plan_source', sa.Integer(), nullable=True),
    sa.Column('plan_status', sa.Integer(), nullable=True),
    sa.Column('strategy_count', sa.Integer(), nullable=True),
    sa.Column('strategy_snapshot', sa.Text(), nullable=True),
    sa.Column('recommend_reason', sa.Text(), nullable=True),
    sa.Column('adjust_note', sa.Text(), nullable=True),
    sa.Column('confirm_user_id', sa.BigInteger(), nullable=True),
    sa.Column('confirm_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_rag_document_strategy_step',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=True),
    sa.Column('pipeline_type', sa.String(length=64), nullable=True),
    sa.Column('strategy_type', sa.Integer(), nullable=True),
    sa.Column('strategy_role', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.Integer(), nullable=True),
    sa.Column('execute_status', sa.Integer(), nullable=True),
    sa.Column('recommend_reason', sa.Text(), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_rag_document_structure_node',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=True),
    sa.Column('parse_task_id', sa.String(length=128), nullable=True),
    sa.Column('node_no', sa.Integer(), nullable=True),
    sa.Column('node_type', sa.Integer(), nullable=True),
    sa.Column('parent_node_id', sa.BigInteger(), nullable=True),
    sa.Column('prev_sibling_node_id', sa.BigInteger(), nullable=True),
    sa.Column('next_sibling_node_id', sa.BigInteger(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('node_code', sa.String(length=128), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('anchor_text', sa.Text(), nullable=True),
    sa.Column('canonical_path', sa.Text(), nullable=True),
    sa.Column('section_path', sa.Text(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('item_index', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_rag_document_task',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=True),
    sa.Column('plan_id', sa.BigInteger(), nullable=True),
    sa.Column('task_type', sa.Integer(), nullable=True),
    sa.Column('task_status', sa.Integer(), nullable=True),
    sa.Column('current_stage', sa.Integer(), nullable=True),
    sa.Column('trigger_source', sa.Integer(), nullable=True),
    sa.Column('strategy_snapshot', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('finish_time', sa.DateTime(), nullable=True),
    sa.Column('cost_millis', sa.BigInteger(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('ext_json', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_rag_document_task_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=128), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('stage_type', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Integer(), nullable=False),
    sa.Column('log_level', sa.Integer(), nullable=False),
    sa.Column('operator_type', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.String(length=128), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_rag_document_task_log_document_id'), 'pipeline_rag_document_task_log', ['document_id'], unique=False)
    op.create_index(op.f('ix_pipeline_rag_document_task_log_task_id'), 'pipeline_rag_document_task_log', ['task_id'], unique=False)
    op.create_table('pipeline_rag_knowledge_route_trace',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('exchange_id', sa.BigInteger(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('rewrite_question', sa.Text(), nullable=True),
    sa.Column('mode', sa.String(length=32), nullable=True),
    sa.Column('top_scopes_json', sa.Text(), nullable=True),
    sa.Column('top_topics_json', sa.Text(), nullable=True),
    sa.Column('top_documents_json', sa.Text(), nullable=True),
    sa.Column('selected_document_id', sa.BigInteger(), nullable=True),
    sa.Column('hit_selected_document', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('route_status', sa.Integer(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_rag_knowledge_route_trace_conversation_id'), 'pipeline_rag_knowledge_route_trace', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_pipeline_rag_knowledge_route_trace_exchange_id'), 'pipeline_rag_knowledge_route_trace', ['exchange_id'], unique=False)
    op.create_table('pipeline_rag_knowledge_scope_node',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), server_default='default', nullable=False),
    sa.Column('scope_code', sa.String(length=64), nullable=False),
    sa.Column('scope_name', sa.String(length=128), nullable=False),
    sa.Column('parent_scope_code', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('aliases', sa.Text(), nullable=True),
    sa.Column('examples', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_rag_knowledge_scope_node_scope_code'), 'pipeline_rag_knowledge_scope_node', ['scope_code'], unique=False)
    op.create_index(op.f('ix_pipeline_rag_knowledge_scope_node_tenant_id'), 'pipeline_rag_knowledge_scope_node', ['tenant_id'], unique=False)
    op.create_table('pipeline_rag_knowledge_topic_node',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), server_default='default', nullable=False),
    sa.Column('topic_code', sa.String(length=64), nullable=False),
    sa.Column('topic_name', sa.String(length=128), nullable=False),
    sa.Column('scope_code', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('aliases', sa.Text(), nullable=True),
    sa.Column('examples', sa.Text(), nullable=True),
    sa.Column('answer_shape', sa.Text(), nullable=True),
    sa.Column('execution_preference', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_rag_knowledge_topic_node_tenant_id'), 'pipeline_rag_knowledge_topic_node', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_pipeline_rag_knowledge_topic_node_topic_code'), 'pipeline_rag_knowledge_topic_node', ['topic_code'], unique=False)
    op.create_table('pipeline_rag_topic_document_relation',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('topic_code', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('relation_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('relation_source', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_evaluation_dataset',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), server_default='default', nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('ground_truth', sa.Text(), nullable=False),
    sa.Column('contexts', sa.Text(), nullable=True),
    sa.Column('exchange_id', sa.BigInteger(), nullable=True),
    sa.Column('conversation_id', sa.String(length=64), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('generated_answer', sa.Text(), nullable=True),
    sa.Column('faithfulness_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('answer_relevancy_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('context_precision_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('context_recall_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('answer_correctness_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('eval_message', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_evaluation_dataset_tenant_id'), 'rag_evaluation_dataset', ['tenant_id'], unique=False)
    op.create_table('shadow_router_record',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('user_selected_doc_ids', sa.Text(), nullable=True),
    sa.Column('system_routed_doc_ids', sa.Text(), nullable=True),
    sa.Column('hit', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('candidate_rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shadow_router_record_conversation_id'), 'shadow_router_record', ['conversation_id'], unique=False)
    op.create_table('document_task',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('doc_id', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=True),
    sa.Column('stage', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=128), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['pipeline_rag_document.doc_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_table('pipeline_rag_document_chunk',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), server_default='default', nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_no', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.Integer(), nullable=True),
    sa.Column('section_path', sa.Text(), nullable=True),
    sa.Column('structure_node_id', sa.BigInteger(), nullable=True),
    sa.Column('structure_node_type', sa.Integer(), nullable=True),
    sa.Column('canonical_path', sa.Text(), nullable=True),
    sa.Column('item_index', sa.Integer(), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('vector_status', sa.Integer(), nullable=True),
    sa.Column('vector_store_type', sa.Integer(), nullable=True),
    sa.Column('vector_id', sa.String(length=128), nullable=True),
    sa.Column('task_id', sa.String(length=128), nullable=True),
    sa.Column('plan_id', sa.BigInteger(), nullable=True),
    sa.Column('parent_block_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['pipeline_rag_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_rag_document_chunk_tenant_id'), 'pipeline_rag_document_chunk', ['tenant_id'], unique=False)
    op.create_table('pipeline_rag_document_profile',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('profile_status', sa.Integer(), nullable=False),
    sa.Column('document_summary', sa.Text(), nullable=True),
    sa.Column('document_type', sa.String(length=64), nullable=True),
    sa.Column('core_topics', sa.Text(), nullable=True),
    sa.Column('example_questions', sa.Text(), nullable=True),
    sa.Column('graph_friendly', sa.Integer(), nullable=True),
    sa.Column('supports_graph_outline', sa.Integer(), nullable=True),
    sa.Column('supports_item_lookup', sa.Integer(), nullable=True),
    sa.Column('supports_graph_assist', sa.Integer(), nullable=True),
    sa.Column('knowledge_domain', sa.String(length=128), nullable=True),
    sa.Column('knowledge_scope_code', sa.String(length=64), nullable=True),
    sa.Column('knowledge_scope_name', sa.String(length=128), nullable=True),
    sa.Column('business_category', sa.String(length=128), nullable=True),
    sa.Column('document_tags', sa.String(length=256), nullable=True),
    sa.Column('profile_source', sa.String(length=64), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['pipeline_rag_document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_rag_document_profile')
    op.drop_index(op.f('ix_pipeline_rag_document_chunk_tenant_id'), table_name='pipeline_rag_document_chunk')
    op.drop_table('pipeline_rag_document_chunk')
    op.drop_table('document_task')
    op.drop_index(op.f('ix_shadow_router_record_conversation_id'), table_name='shadow_router_record')
    op.drop_table('shadow_router_record')
    op.drop_index(op.f('ix_rag_evaluation_dataset_tenant_id'), table_name='rag_evaluation_dataset')
    op.drop_table('rag_evaluation_dataset')
    op.drop_table('pipeline_rag_topic_document_relation')
    op.drop_index(op.f('ix_pipeline_rag_knowledge_topic_node_topic_code'), table_name='pipeline_rag_knowledge_topic_node')
    op.drop_index(op.f('ix_pipeline_rag_knowledge_topic_node_tenant_id'), table_name='pipeline_rag_knowledge_topic_node')
    op.drop_table('pipeline_rag_knowledge_topic_node')
    op.drop_index(op.f('ix_pipeline_rag_knowledge_scope_node_tenant_id'), table_name='pipeline_rag_knowledge_scope_node')
    op.drop_index(op.f('ix_pipeline_rag_knowledge_scope_node_scope_code'), table_name='pipeline_rag_knowledge_scope_node')
    op.drop_table('pipeline_rag_knowledge_scope_node')
    op.drop_index(op.f('ix_pipeline_rag_knowledge_route_trace_exchange_id'), table_name='pipeline_rag_knowledge_route_trace')
    op.drop_index(op.f('ix_pipeline_rag_knowledge_route_trace_conversation_id'), table_name='pipeline_rag_knowledge_route_trace')
    op.drop_table('pipeline_rag_knowledge_route_trace')
    op.drop_index(op.f('ix_pipeline_rag_document_task_log_task_id'), table_name='pipeline_rag_document_task_log')
    op.drop_index(op.f('ix_pipeline_rag_document_task_log_document_id'), table_name='pipeline_rag_document_task_log')
    op.drop_table('pipeline_rag_document_task_log')
    op.drop_table('pipeline_rag_document_task')
    op.drop_table('pipeline_rag_document_structure_node')
    op.drop_table('pipeline_rag_document_strategy_step')
    op.drop_table('pipeline_rag_document_strategy_plan')
    op.drop_table('pipeline_rag_document_parent_block')
    op.drop_index(op.f('ix_pipeline_rag_document_tenant_id'), table_name='pipeline_rag_document')
    op.drop_table('pipeline_rag_document')
    op.drop_index(op.f('ix_pipeline_rag_chat_retrieval_result_exchange_id'), table_name='pipeline_rag_chat_retrieval_result')
    op.drop_index(op.f('ix_pipeline_rag_chat_retrieval_result_dialogue_code'), table_name='pipeline_rag_chat_retrieval_result')
    op.drop_table('pipeline_rag_chat_retrieval_result')
    op.drop_index(op.f('ix_pipeline_rag_chat_memory_summary_dialogue_code'), table_name='pipeline_rag_chat_memory_summary')
    op.drop_table('pipeline_rag_chat_memory_summary')
    op.drop_index(op.f('ix_pipeline_rag_chat_exchange_trace_stage_exchange_id'), table_name='pipeline_rag_chat_exchange_trace_stage')
    op.drop_index(op.f('ix_pipeline_rag_chat_exchange_trace_stage_dialogue_code'), table_name='pipeline_rag_chat_exchange_trace_stage')
    op.drop_table('pipeline_rag_chat_exchange_trace_stage')
    op.drop_index(op.f('ix_pipeline_rag_chat_exchange_dialogue_code'), table_name='pipeline_rag_chat_exchange')
    op.drop_table('pipeline_rag_chat_exchange')
    op.drop_index(op.f('ix_pipeline_rag_chat_dialogue_dialogue_code'), table_name='pipeline_rag_chat_dialogue')
    op.drop_table('pipeline_rag_chat_dialogue')
    op.drop_index(op.f('ix_pipeline_rag_chat_channel_execution_exchange_id'), table_name='pipeline_rag_chat_channel_execution')
    op.drop_index(op.f('ix_pipeline_rag_chat_channel_execution_dialogue_code'), table_name='pipeline_rag_chat_channel_execution')
    op.drop_table('pipeline_rag_chat_channel_execution')
    op.drop_index(op.f('ix_feishu_binding_conversation_id'), table_name='feishu_binding')
    op.drop_index(op.f('ix_feishu_binding_chat_id'), table_name='feishu_binding')
    op.drop_table('feishu_binding')
    op.drop_index(op.f('ix_conversation_session_tenant_id'), table_name='conversation_session')
    op.drop_table('conversation_session')
    op.drop_index(op.f('ix_conversation_rag_evaluation_exchange_id'), table_name='conversation_rag_evaluation')
    op.drop_index(op.f('ix_conversation_rag_evaluation_conversation_id'), table_name='conversation_rag_evaluation')
    op.drop_table('conversation_rag_evaluation')
    op.drop_index(op.f('ix_chat_model_usage_trace_trace_id'), table_name='chat_model_usage_trace')
    op.drop_index(op.f('ix_chat_model_usage_trace_session_id'), table_name='chat_model_usage_trace')
    op.drop_index(op.f('ix_chat_model_usage_trace_exchange_id'), table_name='chat_model_usage_trace')
    op.drop_table('chat_model_usage_trace')
    op.drop_index(op.f('ix_chat_exchange_feedback_exchange_id'), table_name='chat_exchange_feedback')
    op.drop_index(op.f('ix_chat_exchange_feedback_conversation_id'), table_name='chat_exchange_feedback')
    op.drop_table('chat_exchange_feedback')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
