"""Add trace models

Revision ID: 03ee6f4c98b0
Revises: 6bf83d36b1fe
Create Date: 2026-05-23 21:17:00.099414

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03ee6f4c98b0"
down_revision: str | None = "6bf83d36b1fe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_channel_execution",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("conversation_id", sa.String(length=64), nullable=False),
        sa.Column("exchange_id", sa.BigInteger(), nullable=False),
        sa.Column("sub_question", sa.Text(), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("recalled_count", sa.Integer(), nullable=False),
        sa.Column("accepted_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversation_channel_execution_conversation_id"),
        "conversation_channel_execution",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_channel_execution_exchange_id"),
        "conversation_channel_execution",
        ["exchange_id"],
        unique=False,
    )
    op.create_table(
        "conversation_retrieval_result",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("conversation_id", sa.String(length=64), nullable=False),
        sa.Column("exchange_id", sa.BigInteger(), nullable=False),
        sa.Column("sub_question", sa.Text(), nullable=False),
        sa.Column("phase", sa.String(length=32), nullable=False),
        sa.Column("chunk_id", sa.String(length=64), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversation_retrieval_result_conversation_id"),
        "conversation_retrieval_result",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_retrieval_result_exchange_id"),
        "conversation_retrieval_result",
        ["exchange_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_conversation_retrieval_result_exchange_id"),
        table_name="conversation_retrieval_result",
    )
    op.drop_index(
        op.f("ix_conversation_retrieval_result_conversation_id"),
        table_name="conversation_retrieval_result",
    )
    op.drop_table("conversation_retrieval_result")
    op.drop_index(
        op.f("ix_conversation_channel_execution_exchange_id"),
        table_name="conversation_channel_execution",
    )
    op.drop_index(
        op.f("ix_conversation_channel_execution_conversation_id"),
        table_name="conversation_channel_execution",
    )
    op.drop_table("conversation_channel_execution")
    # ### end Alembic commands ###
