"""Add tenant_id for multi-tenancy

Revision ID: 1bf7f017d094
Revises: bd064244934a
Create Date: 2026-05-31 18:03:39.646138

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1bf7f017d094"
down_revision: str | None = "bd064244934a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversation_session",
        sa.Column("tenant_id", sa.String(length=64), server_default="default", nullable=False),
    )
    op.create_index(
        op.f("ix_conversation_session_tenant_id"),
        "conversation_session",
        ["tenant_id"],
        unique=False,
    )
    op.add_column(
        "pipeline_rag_document",
        sa.Column("tenant_id", sa.String(length=64), server_default="default", nullable=False),
    )
    op.create_index(
        op.f("ix_pipeline_rag_document_tenant_id"),
        "pipeline_rag_document",
        ["tenant_id"],
        unique=False,
    )
    op.add_column(
        "pipeline_rag_document_chunk",
        sa.Column("tenant_id", sa.String(length=64), server_default="default", nullable=False),
    )
    op.create_index(
        op.f("ix_pipeline_rag_document_chunk_tenant_id"),
        "pipeline_rag_document_chunk",
        ["tenant_id"],
        unique=False,
    )
    op.add_column(
        "pipeline_rag_knowledge_scope_node",
        sa.Column("tenant_id", sa.String(length=64), server_default="default", nullable=False),
    )
    op.create_index(
        op.f("ix_pipeline_rag_knowledge_scope_node_tenant_id"),
        "pipeline_rag_knowledge_scope_node",
        ["tenant_id"],
        unique=False,
    )
    op.add_column(
        "pipeline_rag_knowledge_topic_node",
        sa.Column("tenant_id", sa.String(length=64), server_default="default", nullable=False),
    )
    op.create_index(
        op.f("ix_pipeline_rag_knowledge_topic_node_tenant_id"),
        "pipeline_rag_knowledge_topic_node",
        ["tenant_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_pipeline_rag_knowledge_topic_node_tenant_id"),
        table_name="pipeline_rag_knowledge_topic_node",
    )
    op.drop_column("pipeline_rag_knowledge_topic_node", "tenant_id")
    op.drop_index(
        op.f("ix_pipeline_rag_knowledge_scope_node_tenant_id"),
        table_name="pipeline_rag_knowledge_scope_node",
    )
    op.drop_column("pipeline_rag_knowledge_scope_node", "tenant_id")
    op.drop_index(
        op.f("ix_pipeline_rag_document_chunk_tenant_id"), table_name="pipeline_rag_document_chunk"
    )
    op.drop_column("pipeline_rag_document_chunk", "tenant_id")
    op.drop_index(op.f("ix_pipeline_rag_document_tenant_id"), table_name="pipeline_rag_document")
    op.drop_column("pipeline_rag_document", "tenant_id")
    op.drop_index(op.f("ix_conversation_session_tenant_id"), table_name="conversation_session")
    op.drop_column("conversation_session", "tenant_id")
    # ### end Alembic commands ###
    # ### end Alembic commands ###
