"""init

Revision ID: 6bf83d36b1fe
Revises: bbd8f7c79c98
Create Date: 2026-05-23 18:11:30.192504

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "6bf83d36b1fe"
down_revision: str | None = "bbd8f7c79c98"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
