"""init

Revision ID: bbd8f7c79c98
Revises:
Create Date: 2026-05-23 14:41:39.202119

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bbd8f7c79c98"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_user",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password", sa.String(length=128), nullable=False),
        sa.Column("nickname", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "conversation_memory",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("conversation_id", sa.String(length=64), nullable=False),
        sa.Column("strategy", sa.String(length=32), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("window_json", sa.Text(), nullable=True),
        sa.Column("summary_pointer", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("conversation_id"),
    )
    op.create_table(
        "conversation_session",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("conversation_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=True),
        sa.Column("chat_mode", sa.String(length=32), nullable=False),
        sa.Column("memory_strategy", sa.String(length=32), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("conversation_id"),
    )
    op.create_table(
        "document_strategy",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("doc_id", sa.String(length=64), nullable=False),
        sa.Column("strategy_type", sa.String(length=32), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("config_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "knowledge_scope",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("scope_code", sa.String(length=64), nullable=False),
        sa.Column("scope_name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope_code"),
    )
    op.create_table(
        "shadow_router_record",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("conversation_id", sa.String(length=64), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("user_selected_doc_ids", sa.Text(), nullable=True),
        sa.Column("system_routed_doc_ids", sa.Text(), nullable=True),
        sa.Column("hit", sa.Boolean(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("candidate_rank", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_shadow_router_record_conversation_id"),
        "shadow_router_record",
        ["conversation_id"],
        unique=False,
    )
    op.create_table(
        "conversation_exchange",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("conversation_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.BigInteger(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column("execution_mode", sa.String(length=32), nullable=True),
        sa.Column("tokens_used", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["conversation_session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversation_exchange_conversation_id"),
        "conversation_exchange",
        ["conversation_id"],
        unique=False,
    )
    op.create_table(
        "knowledge_topic",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("scope_id", sa.BigInteger(), nullable=False),
        sa.Column("topic_code", sa.String(length=64), nullable=False),
        sa.Column("topic_name", sa.String(length=128), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["scope_id"],
            ["knowledge_scope.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "document",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("doc_id", sa.String(length=64), nullable=False),
        sa.Column("scope_id", sa.BigInteger(), nullable=True),
        sa.Column("topic_id", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("file_name", sa.String(length=256), nullable=False),
        sa.Column("file_type", sa.String(length=32), nullable=False),
        sa.Column("storage_path", sa.String(length=512), nullable=False),
        sa.Column("parse_status", sa.String(length=32), nullable=False),
        sa.Column("index_status", sa.String(length=32), nullable=False),
        sa.Column("content_quality", sa.String(length=32), nullable=True),
        sa.Column("tags", sa.String(length=512), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["scope_id"],
            ["knowledge_scope.id"],
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["knowledge_topic.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("doc_id"),
    )
    op.create_table(
        "document_chunk",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("chunk_id", sa.String(length=64), nullable=False),
        sa.Column("doc_id", sa.String(length=64), nullable=False),
        sa.Column("parent_chunk_id", sa.String(length=64), nullable=True),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("chunk_type", sa.String(length=32), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("section_title", sa.String(length=256), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["doc_id"],
            ["document.doc_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chunk_id"),
    )
    op.create_table(
        "document_task",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("doc_id", sa.String(length=64), nullable=False),
        sa.Column("task_type", sa.String(length=32), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("celery_task_id", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["doc_id"],
            ["document.doc_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id"),
    )
    op.drop_index(
        op.f("idx_pipeline_rag_chat_memory_summary_cover"),
        table_name="pipeline_rag_chat_memory_summary",
    )
    op.drop_index(
        op.f("idx_pipeline_rag_chat_memory_summary_edit_time"),
        table_name="pipeline_rag_chat_memory_summary",
    )
    op.drop_index(
        op.f("uk_pipeline_rag_chat_memory_summary_dialogue"),
        table_name="pipeline_rag_chat_memory_summary",
    )
    op.drop_table("pipeline_rag_chat_memory_summary")
    op.drop_index(
        op.f("idx_pipeline_rag_chat_trace_dialogue"),
        table_name="pipeline_rag_chat_exchange_trace_stage",
    )
    op.drop_index(
        op.f("idx_pipeline_rag_chat_trace_exchange"),
        table_name="pipeline_rag_chat_exchange_trace_stage",
    )
    op.drop_index(
        op.f("idx_pipeline_rag_chat_trace_stage_code"),
        table_name="pipeline_rag_chat_exchange_trace_stage",
    )
    op.drop_index(
        op.f("idx_pipeline_rag_chat_trace_trace_id"),
        table_name="pipeline_rag_chat_exchange_trace_stage",
    )
    op.drop_table("pipeline_rag_chat_exchange_trace_stage")
    op.drop_index(op.f("idx_document_type"), table_name="pipeline_rag_document_profile")
    op.drop_index(op.f("idx_profile_status"), table_name="pipeline_rag_document_profile")
    op.drop_index(op.f("idx_status"), table_name="pipeline_rag_document_profile")
    op.drop_index(op.f("uk_document_id"), table_name="pipeline_rag_document_profile")
    op.drop_table("pipeline_rag_document_profile")
    op.drop_index(
        op.f("idx_pipeline_rag_chat_dialogue_code_status"), table_name="pipeline_rag_chat_dialogue"
    )
    op.drop_index(
        op.f("idx_pipeline_rag_chat_dialogue_edit_time"), table_name="pipeline_rag_chat_dialogue"
    )
    op.drop_index(
        op.f("idx_pipeline_rag_chat_dialogue_stage_status"), table_name="pipeline_rag_chat_dialogue"
    )
    op.drop_table("pipeline_rag_chat_dialogue")
    op.drop_index(
        op.f("idx_retrieval_result_channel"), table_name="pipeline_rag_chat_retrieval_result"
    )
    op.drop_index(
        op.f("idx_retrieval_result_document"), table_name="pipeline_rag_chat_retrieval_result"
    )
    op.drop_index(
        op.f("idx_retrieval_result_exchange"), table_name="pipeline_rag_chat_retrieval_result"
    )
    op.drop_index(
        op.f("idx_retrieval_result_sub_question"), table_name="pipeline_rag_chat_retrieval_result"
    )
    op.drop_index(
        op.f("idx_retrieval_result_trace"), table_name="pipeline_rag_chat_retrieval_result"
    )
    op.drop_table("pipeline_rag_chat_retrieval_result")
    op.drop_index(op.f("idx_parent_scope_code"), table_name="pipeline_rag_knowledge_scope_node")
    op.drop_index(op.f("idx_status"), table_name="pipeline_rag_knowledge_scope_node")
    op.drop_index(op.f("uk_scope_code"), table_name="pipeline_rag_knowledge_scope_node")
    op.drop_table("pipeline_rag_knowledge_scope_node")
    op.drop_index(op.f("idx_scope_code"), table_name="pipeline_rag_knowledge_topic_node")
    op.drop_index(op.f("idx_status"), table_name="pipeline_rag_knowledge_topic_node")
    op.drop_index(op.f("uk_topic_code"), table_name="pipeline_rag_knowledge_topic_node")
    op.drop_table("pipeline_rag_knowledge_topic_node")
    op.drop_index(op.f("idx_graph_checkpoint_thread_saved"), table_name="GRAPH_CHECKPOINT")
    op.drop_table("GRAPH_CHECKPOINT")
    op.drop_index(op.f("idx_document_id"), table_name="pipeline_rag_document_chunk")
    op.drop_index(op.f("idx_parent_block_id"), table_name="pipeline_rag_document_chunk")
    op.drop_index(op.f("idx_vector_status"), table_name="pipeline_rag_document_chunk")
    op.drop_index(op.f("uk_task_chunk_no"), table_name="pipeline_rag_document_chunk")
    op.drop_table("pipeline_rag_document_chunk")
    op.drop_index(op.f("idx_document_id"), table_name="pipeline_rag_document_strategy_step")
    op.drop_index(op.f("idx_pipeline_type"), table_name="pipeline_rag_document_strategy_step")
    op.drop_index(op.f("idx_strategy_type"), table_name="pipeline_rag_document_strategy_step")
    op.drop_index(
        op.f("uk_plan_pipeline_step_no"), table_name="pipeline_rag_document_strategy_step"
    )
    op.drop_table("pipeline_rag_document_strategy_step")
    op.drop_index(
        op.f("idx_pipeline_rag_chat_exchange_create_time"), table_name="pipeline_rag_chat_exchange"
    )
    op.drop_index(
        op.f("idx_pipeline_rag_chat_exchange_dialogue_status"),
        table_name="pipeline_rag_chat_exchange",
    )
    op.drop_index(
        op.f("idx_pipeline_rag_chat_exchange_state_status"), table_name="pipeline_rag_chat_exchange"
    )
    op.drop_table("pipeline_rag_chat_exchange")
    op.drop_index(
        op.f("idx_channel_exec_channel"), table_name="pipeline_rag_chat_channel_execution"
    )
    op.drop_index(
        op.f("idx_channel_exec_exchange"), table_name="pipeline_rag_chat_channel_execution"
    )
    op.drop_index(op.f("idx_channel_exec_trace"), table_name="pipeline_rag_chat_channel_execution")
    op.drop_table("pipeline_rag_chat_channel_execution")
    op.drop_index(op.f("idx_document_id"), table_name="pipeline_rag_document_task_log")
    op.drop_index(op.f("idx_stage_type"), table_name="pipeline_rag_document_task_log")
    op.drop_index(op.f("idx_task_id"), table_name="pipeline_rag_document_task_log")
    op.drop_table("pipeline_rag_document_task_log")
    op.drop_index(op.f("idx_document_id"), table_name="pipeline_rag_document_parent_block")
    op.drop_index(op.f("idx_task_id"), table_name="pipeline_rag_document_parent_block")
    op.drop_index(op.f("uk_task_parent_no"), table_name="pipeline_rag_document_parent_block")
    op.drop_table("pipeline_rag_document_parent_block")
    op.drop_index(
        op.f("uk_stage_benchmark_code_mode"), table_name="pipeline_rag_chat_stage_benchmark"
    )
    op.drop_table("pipeline_rag_chat_stage_benchmark")
    op.drop_index(op.f("idx_document_id"), table_name="pipeline_rag_topic_document_relation")
    op.drop_index(op.f("idx_status"), table_name="pipeline_rag_topic_document_relation")
    op.drop_index(op.f("idx_topic_code"), table_name="pipeline_rag_topic_document_relation")
    op.drop_index(op.f("uk_topic_document"), table_name="pipeline_rag_topic_document_relation")
    op.drop_table("pipeline_rag_topic_document_relation")
    op.drop_index(op.f("idx_current_plan_id"), table_name="pipeline_rag_document")
    op.drop_index(op.f("idx_index_status"), table_name="pipeline_rag_document")
    op.drop_index(op.f("idx_knowledge_scope_code"), table_name="pipeline_rag_document")
    op.drop_index(op.f("idx_object_name"), table_name="pipeline_rag_document")
    op.drop_index(op.f("idx_parse_status"), table_name="pipeline_rag_document")
    op.drop_index(op.f("idx_strategy_status"), table_name="pipeline_rag_document")
    op.drop_table("pipeline_rag_document")
    op.drop_index(op.f("idx_document_task"), table_name="pipeline_rag_document_task")
    op.drop_index(op.f("idx_plan_id"), table_name="pipeline_rag_document_task")
    op.drop_index(op.f("idx_task_status"), table_name="pipeline_rag_document_task")
    op.drop_table("pipeline_rag_document_task")
    op.drop_index(op.f("IDX_GRAPH_THREAD_NAME_RELEASED"), table_name="GRAPH_THREAD")
    op.drop_table("GRAPH_THREAD")
    op.drop_index(op.f("idx_document_id"), table_name="pipeline_rag_document_structure_node")
    op.drop_index(op.f("idx_node_type"), table_name="pipeline_rag_document_structure_node")
    op.drop_index(op.f("idx_parent_node_id"), table_name="pipeline_rag_document_structure_node")
    op.drop_index(op.f("idx_parse_task_id"), table_name="pipeline_rag_document_structure_node")
    op.drop_index(op.f("uk_parse_task_node_no"), table_name="pipeline_rag_document_structure_node")
    op.drop_table("pipeline_rag_document_structure_node")
    op.drop_index(op.f("idx_plan_status"), table_name="pipeline_rag_document_strategy_plan")
    op.drop_index(op.f("uk_document_version"), table_name="pipeline_rag_document_strategy_plan")
    op.drop_table("pipeline_rag_document_strategy_plan")
    op.drop_index(
        op.f("idx_conversation_exchange"), table_name="pipeline_rag_knowledge_route_trace"
    )
    op.drop_index(op.f("idx_create_time"), table_name="pipeline_rag_knowledge_route_trace")
    op.drop_index(op.f("idx_route_status"), table_name="pipeline_rag_knowledge_route_trace")
    op.drop_index(op.f("idx_selected_document_id"), table_name="pipeline_rag_knowledge_route_trace")
    op.drop_table("pipeline_rag_knowledge_route_trace")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pipeline_rag_knowledge_route_trace",
        sa.Column("id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="ä¸»é”®id"),
        sa.Column(
            "conversation_id", mysql.VARCHAR(length=64), nullable=True, comment="ä¼šè¯\x9did"
        ),
        sa.Column(
            "exchange_id", mysql.BIGINT(), autoincrement=False, nullable=True, comment="è½®æ¬¡id"
        ),
        sa.Column("question", mysql.TEXT(), nullable=True, comment="åŽŸå§‹é—®é¢˜"),
        sa.Column("rewrite_question", mysql.TEXT(), nullable=True, comment="æ”¹å†™é—®é¢˜"),
        sa.Column(
            "mode",
            mysql.VARCHAR(length=32),
            nullable=True,
            comment="è¿\x90è¡Œæ¨¡å¼\x8f shadow/auto",
        ),
        sa.Column(
            "top_scopes_json", mysql.TEXT(), nullable=True, comment="å€™é€‰çŸ¥è¯†èŒƒå›´ JSON"
        ),
        sa.Column("top_topics_json", mysql.TEXT(), nullable=True, comment="å€™é€‰ä¸»é¢˜ JSON"),
        sa.Column("top_documents_json", mysql.TEXT(), nullable=True, comment="å€™é€‰æ–‡æ¡£ JSON"),
        sa.Column(
            "selected_document_id",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="å½“å‰\x8då®žé™…ä½¿ç”¨æ–‡æ¡£id",
        ),
        sa.Column(
            "hit_selected_document",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=True,
            comment="å€™é€‰æ˜¯å\x90¦å‘½ä¸\xadå®žé™…æ–‡æ¡£",
        ),
        sa.Column(
            "confidence",
            mysql.DECIMAL(precision=8, scale=4),
            server_default=sa.text("'0.0000'"),
            nullable=True,
            comment="æ•´ä½“ç½®ä¿¡åº¦",
        ),
        sa.Column(
            "route_status",
            mysql.TINYINT(),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=True,
            comment="è·¯ç”±çŠ¶æ€\x81 1:æˆ\x90åŠŸ 2:ä½Žç½®ä¿¡ 3:å¤±è´¥",
        ),
        sa.Column(
            "error_msg", mysql.VARCHAR(length=1024), nullable=True, comment="å¤±è´¥åŽŸå›\xa0"
        ),
        sa.Column("create_time", mysql.DATETIME(), nullable=True, comment="åˆ›å»ºæ—¶é—´"),
        sa.Column("edit_time", mysql.DATETIME(), nullable=True, comment="ç¼–è¾‘æ—¶é—´"),
        sa.Column(
            "status",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=True,
            comment="1:æ\xad£å¸¸ 0:åˆ\xa0é™¤",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="çŸ¥è¯†è·¯ç”±å½±å\xad\x90è¿½è¸ªè¡¨",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_comment="çŸ¥è¯†è·¯ç”±å½±å\xad\x90è¿½è¸ªè¡¨",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("idx_selected_document_id"),
        "pipeline_rag_knowledge_route_trace",
        ["selected_document_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_route_status"),
        "pipeline_rag_knowledge_route_trace",
        ["route_status"],
        unique=False,
    )
    op.create_index(
        op.f("idx_create_time"), "pipeline_rag_knowledge_route_trace", ["create_time"], unique=False
    )
    op.create_index(
        op.f("idx_conversation_exchange"),
        "pipeline_rag_knowledge_route_trace",
        ["conversation_id", "exchange_id"],
        unique=False,
    )
    op.create_table(
        "pipeline_rag_document_strategy_plan",
        sa.Column("id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="ä¸»é”®id"),
        sa.Column(
            "document_id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="æ–‡æ¡£id"
        ),
        sa.Column(
            "plan_version",
            mysql.INTEGER(),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=False,
            comment="æ–¹æ¡ˆç‰ˆæœ¬å\x8f·",
        ),
        sa.Column(
            "plan_source",
            mysql.TINYINT(),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=False,
            comment="æ–¹æ¡ˆæ\x9d¥æº\x90 1:ç³»ç»ŸæŽ¨è\x8d\x90 2:ç”¨æˆ·è°ƒæ•´",
        ),
        sa.Column(
            "plan_status",
            mysql.TINYINT(),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=False,
            comment="æ–¹æ¡ˆçŠ¶æ€\x81 1:å¾…ç¡®è®¤ 2:å·²ç¡®è®¤ 3:å·²æ‰§è¡Œ 4:å·²åºŸå¼ƒ",
        ),
        sa.Column(
            "strategy_count",
            mysql.TINYINT(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
            comment="ç\xad–ç•¥æ•°é‡\x8f",
        ),
        sa.Column(
            "strategy_snapshot",
            mysql.VARCHAR(length=255),
            nullable=True,
            comment="ç\xad–ç•¥å¿«ç…§ï¼Œä¾‹:1,2,3",
        ),
        sa.Column("recommend_reason", mysql.TEXT(), nullable=True, comment="æŽ¨è\x8d\x90åŽŸå›\xa0"),
        sa.Column("adjust_note", mysql.VARCHAR(length=500), nullable=True, comment="è°ƒæ•´è¯´æ˜Ž"),
        sa.Column(
            "confirm_user_id",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="ç¡®è®¤äººid",
        ),
        sa.Column("confirm_time", mysql.DATETIME(), nullable=True, comment="ç¡®è®¤æ—¶é—´"),
        sa.Column("create_time", mysql.DATETIME(), nullable=True, comment="åˆ›å»ºæ—¶é—´"),
        sa.Column("edit_time", mysql.DATETIME(), nullable=True, comment="ç¼–è¾‘æ—¶é—´"),
        sa.Column(
            "status",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=True,
            comment="1:æ\xad£å¸¸ 0:åˆ\xa0é™¤",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="æ–‡æ¡£ç\xad–ç•¥æ–¹æ¡ˆè¡¨",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_comment="æ–‡æ¡£ç\xad–ç•¥æ–¹æ¡ˆè¡¨",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("uk_document_version"),
        "pipeline_rag_document_strategy_plan",
        ["document_id", "plan_version"],
        unique=True,
    )
    op.create_index(
        op.f("idx_plan_status"),
        "pipeline_rag_document_strategy_plan",
        ["plan_status"],
        unique=False,
    )
    op.create_table(
        "pipeline_rag_document_structure_node",
        sa.Column("id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="ä¸»é”®id"),
        sa.Column(
            "document_id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="æ–‡æ¡£id"
        ),
        sa.Column(
            "parse_task_id",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=False,
            comment="è§£æž\x90ä»»åŠ¡id",
        ),
        sa.Column(
            "node_no",
            mysql.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="å½“å‰\x8dæ–‡æ¡£å†…çš„ç¨³å®šé¡ºåº\x8få\x8f·",
        ),
        sa.Column(
            "node_type",
            mysql.TINYINT(),
            autoincrement=False,
            nullable=False,
            comment="èŠ‚ç‚¹ç±»åž‹ 1:æ–‡æ¡£æ\xa0¹èŠ‚ç‚¹ 2:ç«\xa0èŠ‚èŠ‚ç‚¹ 3:æ\xad¥éª¤èŠ‚ç‚¹ 4:åˆ—è¡¨é¡¹èŠ‚ç‚¹",
        ),
        sa.Column(
            "parent_node_id",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="çˆ¶èŠ‚ç‚¹id",
        ),
        sa.Column(
            "prev_sibling_node_id",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="ä¸Šä¸€ä¸ªå\x90Œçº§èŠ‚ç‚¹id",
        ),
        sa.Column(
            "next_sibling_node_id",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="ä¸‹ä¸€ä¸ªå\x90Œçº§èŠ‚ç‚¹id",
        ),
        sa.Column(
            "depth",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
            comment="èŠ‚ç‚¹æ·±åº¦",
        ),
        sa.Column(
            "node_code",
            mysql.VARCHAR(length=128),
            nullable=True,
            comment="èŠ‚ç‚¹ç¼–ç\xa0\x81ï¼Œä¾‹å¦‚ 1.2 / ç¬¬ä¸€ç«\xa0 / 4",
        ),
        sa.Column("title", mysql.VARCHAR(length=1000), nullable=True, comment="èŠ‚ç‚¹æ\xa0‡é¢˜"),
        sa.Column(
            "anchor_text",
            mysql.VARCHAR(length=1000),
            nullable=True,
            comment="ä¾›å¯¼èˆªå’Œé”šç‚¹ä½¿ç”¨çš„çŸ\xadé”šæ–‡æœ¬",
        ),
        sa.Column(
            "canonical_path",
            mysql.VARCHAR(length=1000),
            nullable=True,
            comment="èŠ‚ç‚¹ç¨³å®šè·¯å¾„",
        ),
        sa.Column(
            "section_path",
            mysql.VARCHAR(length=1000),
            nullable=True,
            comment="å…¼å®¹çŽ°æœ‰ç³»ç»Ÿçš„ç«\xa0èŠ‚è·¯å¾„æ–‡æœ¬",
        ),
        sa.Column("content_text", mysql.LONGTEXT(), nullable=True, comment="èŠ‚ç‚¹æ\xad£æ–‡"),
        sa.Column(
            "item_index",
            mysql.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="åˆ—è¡¨é¡¹/æ\xad¥éª¤é¡¹åº\x8få\x8f·",
        ),
        sa.Column("create_time", mysql.DATETIME(), nullable=True, comment="åˆ›å»ºæ—¶é—´"),
        sa.Column("edit_time", mysql.DATETIME(), nullable=True, comment="ç¼–è¾‘æ—¶é—´"),
        sa.Column(
            "status",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=True,
            comment="1:æ\xad£å¸¸ 0:åˆ\xa0é™¤",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="æ–‡æ¡£ç»“æž„èŠ‚ç‚¹è¡¨",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_comment="æ–‡æ¡£ç»“æž„èŠ‚ç‚¹è¡¨",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("uk_parse_task_node_no"),
        "pipeline_rag_document_structure_node",
        ["parse_task_id", "node_no"],
        unique=True,
    )
    op.create_index(
        op.f("idx_parse_task_id"),
        "pipeline_rag_document_structure_node",
        ["parse_task_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_parent_node_id"),
        "pipeline_rag_document_structure_node",
        ["parent_node_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_node_type"), "pipeline_rag_document_structure_node", ["node_type"], unique=False
    )
    op.create_index(
        op.f("idx_document_id"),
        "pipeline_rag_document_structure_node",
        ["document_id"],
        unique=False,
    )
    op.create_table(
        "GRAPH_THREAD",
        sa.Column(
            "thread_id",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=36),
            nullable=False,
            comment="Graph å†…éƒ¨çº¿ç¨‹ä¸»é”®",
        ),
        sa.Column(
            "thread_name",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=255),
            nullable=False,
            comment="ä¸šåŠ¡çº¿ç¨‹å\x90\x8dï¼Œé€šå¸¸å°±æ˜¯ conversationId",
        ),
        sa.Column(
            "is_released",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
            comment="æ˜¯å\x90¦å·²ç»\x8fè¢«é‡Šæ”¾",
        ),
        sa.PrimaryKeyConstraint("thread_id"),
        comment="Spring AI Alibaba Graph çº¿ç¨‹è¡¨",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_comment="Spring AI Alibaba Graph çº¿ç¨‹è¡¨",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("IDX_GRAPH_THREAD_NAME_RELEASED"),
        "GRAPH_THREAD",
        ["thread_name", "is_released"],
        unique=True,
    )
    op.create_table(
        "pipeline_rag_document_task",
        sa.Column("id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="ä¸»é”®id"),
        sa.Column(
            "document_id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="æ–‡æ¡£id"
        ),
        sa.Column(
            "plan_id", mysql.BIGINT(), autoincrement=False, nullable=True, comment="æ‰§è¡Œæ–¹æ¡ˆid"
        ),
        sa.Column(
            "task_type",
            mysql.TINYINT(),
            autoincrement=False,
            nullable=False,
            comment="ä»»åŠ¡ç±»åž‹ 1:è§£æž\x90è·¯ç”± 2:æž„å»ºç´¢å¼•",
        ),
        sa.Column(
            "task_status",
            mysql.TINYINT(),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=False,
            comment="ä»»åŠ¡çŠ¶æ€\x81 1:æ–°å»º 2:è¿›è¡Œä¸\xad 3:æˆ\x90åŠŸ 4:å¤±è´¥ 5:å·²å\x8f–æ¶ˆ",
        ),
        sa.Column(
            "current_stage",
            mysql.TINYINT(),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=False,
            comment="å½“å‰\x8dé˜¶æ®µ 1:æ–‡ä»¶ä¸Šä¼\xa0 2:å†…å®¹è§£æž\x90 3:ç\xad–ç•¥è·¯ç”± 4:ç\xad–ç•¥ç¡®è®¤ 5:åˆ‡å\x9d—æ‰§è¡Œ 6:åˆ‡å\x9d—å\x90Žå¤„ç\x90† 7:å\x90‘é‡\x8fåŒ– 8:å…¥åº“å®Œæˆ\x90",
        ),
        sa.Column(
            "trigger_source",
            mysql.TINYINT(),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=False,
            comment="è§¦å\x8f‘æ\x9d¥æº\x90 1:ç³»ç»Ÿè‡ªåŠ¨ 2:ç”¨æˆ·æ‰‹åŠ¨",
        ),
        sa.Column(
            "strategy_snapshot",
            mysql.VARCHAR(length=255),
            nullable=True,
            comment="æ‰§è¡Œæ—¶ç\xad–ç•¥å¿«ç…§ï¼Œä¾‹:1,2,3",
        ),
        sa.Column(
            "retry_count",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
            comment="é‡\x8dè¯•æ¬¡æ•°",
        ),
        sa.Column("start_time", mysql.DATETIME(), nullable=True, comment="å¼€å§‹æ—¶é—´"),
        sa.Column("finish_time", mysql.DATETIME(), nullable=True, comment="ç»“æ\x9dŸæ—¶é—´"),
        sa.Column(
            "cost_millis",
            mysql.BIGINT(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="è€—æ—¶æ¯«ç§’",
        ),
        sa.Column("error_code", mysql.VARCHAR(length=64), nullable=True, comment="é”™è¯¯ç\xa0\x81"),
        sa.Column(
            "error_msg", mysql.VARCHAR(length=1000), nullable=True, comment="é”™è¯¯ä¿¡æ\x81¯"
        ),
        sa.Column("ext_json", mysql.TEXT(), nullable=True, comment="æ‰©å±•ä¿¡æ\x81¯JSON"),
        sa.Column("create_time", mysql.DATETIME(), nullable=True, comment="åˆ›å»ºæ—¶é—´"),
        sa.Column("edit_time", mysql.DATETIME(), nullable=True, comment="ç¼–è¾‘æ—¶é—´"),
        sa.Column(
            "status",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=True,
            comment="1:æ\xad£å¸¸ 0:åˆ\xa0é™¤",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="æ–‡æ¡£ä»»åŠ¡è¡¨",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_comment="æ–‡æ¡£ä»»åŠ¡è¡¨",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("idx_task_status"), "pipeline_rag_document_task", ["task_status"], unique=False
    )
    op.create_index(op.f("idx_plan_id"), "pipeline_rag_document_task", ["plan_id"], unique=False)
    op.create_index(
        op.f("idx_document_task"),
        "pipeline_rag_document_task",
        ["document_id", "task_type"],
        unique=False,
    )
    op.create_table(
        "pipeline_rag_document",
        sa.Column("id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="ä¸»é”®id"),
        sa.Column(
            "document_name", mysql.VARCHAR(length=255), nullable=False, comment="æ–‡æ¡£å\x90\x8dç§°"
        ),
        sa.Column(
            "original_file_name",
            mysql.VARCHAR(length=255),
            nullable=False,
            comment="åŽŸå§‹æ–‡ä»¶å\x90\x8d",
        ),
        sa.Column(
            "file_type",
            mysql.TINYINT(),
            autoincrement=False,
            nullable=False,
            comment="æ–‡ä»¶ç±»åž‹ 1:PDF 2:DOC 3:DOCX 4:TXT 5:MD 6:HTML",
        ),
        sa.Column("mime_type", mysql.VARCHAR(length=128), nullable=True, comment="MIMEç±»åž‹"),
        sa.Column(
            "file_size",
            mysql.BIGINT(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="æ–‡ä»¶å¤§å°\x8f(byte)",
        ),
        sa.Column(
            "storage_type",
            mysql.TINYINT(),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=False,
            comment="å\xad˜å‚¨ç±»åž‹ 1:MinIO",
        ),
        sa.Column(
            "bucket_name", mysql.VARCHAR(length=128), nullable=True, comment="bucketå\x90\x8dç§°"
        ),
        sa.Column(
            "object_name", mysql.VARCHAR(length=512), nullable=True, comment="å¯¹è±¡å\x90\x8dç§°"
        ),
        sa.Column(
            "object_url", mysql.VARCHAR(length=1024), nullable=True, comment="æ–‡ä»¶è®¿é—®åœ°å\x9d€"
        ),
        sa.Column(
            "parse_status",
            mysql.TINYINT(),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=False,
            comment="è§£æž\x90çŠ¶æ€\x81 1:å¾…è§£æž\x90 2:è§£æž\x90ä¸\xad 3:è§£æž\x90æˆ\x90åŠŸ 4:è§£æž\x90å¤±è´¥",
        ),
        sa.Column(
            "strategy_status",
            mysql.TINYINT(),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=False,
            comment="ç\xad–ç•¥çŠ¶æ€\x81 1:å¾…æŽ¨è\x8d\x90 2:å·²æŽ¨è\x8d\x90 3:å·²ç¡®è®¤ 4:å·²å¤±æ•ˆ",
        ),
        sa.Column(
            "index_status",
            mysql.TINYINT(),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=False,
            comment="ç´¢å¼•çŠ¶æ€\x81 1:å¾…æž„å»º 2:æž„å»ºä¸\xad 3:æž„å»ºæˆ\x90åŠŸ 4:æž„å»ºå¤±è´¥",
        ),
        sa.Column(
            "char_count",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="è§£æž\x90å\x90Žå\xad—ç¬¦æ•°",
        ),
        sa.Column(
            "token_count",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="è§£æž\x90å\x90Žtokenä¼°ç®—æ•°",
        ),
        sa.Column(
            "structure_level",
            mysql.TINYINT(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="ç»“æž„åŒ–ç¨‹åº¦ 0:æœªçŸ¥ 1:ä½Ž 2:ä¸\xad 3:é«˜",
        ),
        sa.Column(
            "content_quality_level",
            mysql.TINYINT(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="å†…å®¹è´¨é‡\x8f 0:æœªçŸ¥ 1:ä½Ž 2:ä¸\xad 3:é«˜",
        ),
        sa.Column(
            "parse_text_path",
            mysql.VARCHAR(length=512),
            nullable=True,
            comment="è§£æž\x90æ–‡æœ¬å\xad˜å‚¨è·¯å¾„",
        ),
        sa.Column(
            "parse_error_msg",
            mysql.VARCHAR(length=1000),
            nullable=True,
            comment="è§£æž\x90å¤±è´¥åŽŸå›\xa0",
        ),
        sa.Column(
            "knowledge_scope_code",
            mysql.VARCHAR(length=64),
            nullable=True,
            comment="ä¸šåŠ¡çŸ¥è¯†åŸŸç¼–ç\xa0\x81ï¼Œä¾‹å¦‚ oa / crm / finance",
        ),
        sa.Column(
            "knowledge_scope_name",
            mysql.VARCHAR(length=128),
            nullable=True,
            comment="ä¸šåŠ¡çŸ¥è¯†åŸŸå\x90\x8dç§°ï¼Œä¾‹å¦‚ OAç³»ç»Ÿ / CRMç³»ç»Ÿ",
        ),
        sa.Column(
            "business_category",
            mysql.VARCHAR(length=128),
            nullable=True,
            comment="ä¸šåŠ¡åˆ†ç±»ï¼Œä¾‹å¦‚ æµ\x81ç¨‹ / è§„åˆ™ / æ“\x8dä½œæ‰‹å†Œ",
        ),
        sa.Column(
            "document_tags",
            mysql.VARCHAR(length=512),
            nullable=True,
            comment="é€—å\x8f·åˆ†éš”æ\xa0‡ç\xad¾å¿«ç…§",
        ),
        sa.Column(
            "current_plan_id",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="å½“å‰\x8dç\xad–ç•¥æ–¹æ¡ˆid",
        ),
        sa.Column(
            "last_parse_task_id",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="æœ€è¿‘ä¸€æ¬¡æˆ\x90åŠŸè§£æž\x90ä»»åŠ¡id",
        ),
        sa.Column(
            "structure_node_count",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="æœ€è¿‘ä¸€æ¬¡ç»“æž„åŒ–è§£æž\x90ç”Ÿæˆ\x90çš„èŠ‚ç‚¹æ•°",
        ),
        sa.Column(
            "last_index_task_id",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="æœ€è¿‘ä¸€æ¬¡ç´¢å¼•ä»»åŠ¡id",
        ),
        sa.Column("create_time", mysql.DATETIME(), nullable=True, comment="åˆ›å»ºæ—¶é—´"),
        sa.Column("edit_time", mysql.DATETIME(), nullable=True, comment="ç¼–è¾‘æ—¶é—´"),
        sa.Column(
            "status",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=True,
            comment="1:æ\xad£å¸¸ 0:åˆ\xa0é™¤",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="æ–‡æ¡£è¡¨",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_comment="æ–‡æ¡£è¡¨",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("idx_strategy_status"), "pipeline_rag_document", ["strategy_status"], unique=False
    )
    op.create_index(
        op.f("idx_parse_status"), "pipeline_rag_document", ["parse_status"], unique=False
    )
    op.create_index(op.f("idx_object_name"), "pipeline_rag_document", ["object_name"], unique=False)
    op.create_index(
        op.f("idx_knowledge_scope_code"),
        "pipeline_rag_document",
        ["knowledge_scope_code"],
        unique=False,
    )
    op.create_index(
        op.f("idx_index_status"), "pipeline_rag_document", ["index_status"], unique=False
    )
    op.create_index(
        op.f("idx_current_plan_id"), "pipeline_rag_document", ["current_plan_id"], unique=False
    )
    op.create_table(
        "pipeline_rag_topic_document_relation",
        sa.Column("id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="ä¸»é”®id"),
        sa.Column(
            "topic_code", mysql.VARCHAR(length=64), nullable=False, comment="ä¸»é¢˜ç¼–ç\xa0\x81"
        ),
        sa.Column(
            "document_id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="æ–‡æ¡£id"
        ),
        sa.Column(
            "relation_score",
            mysql.DECIMAL(precision=8, scale=4),
            server_default=sa.text("'0.0000'"),
            nullable=True,
            comment="å…³è\x81”åˆ†æ•°",
        ),
        sa.Column(
            "relation_source",
            mysql.VARCHAR(length=64),
            nullable=True,
            comment="å…³è\x81”æ\x9d¥æº\x90 auto/manual/mixed",
        ),
        sa.Column(
            "reason", mysql.VARCHAR(length=1024), nullable=True, comment="å…³è\x81”åŽŸå›\xa0"
        ),
        sa.Column("create_time", mysql.DATETIME(), nullable=True, comment="åˆ›å»ºæ—¶é—´"),
        sa.Column("edit_time", mysql.DATETIME(), nullable=True, comment="ç¼–è¾‘æ—¶é—´"),
        sa.Column(
            "status",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=True,
            comment="1:æ\xad£å¸¸ 0:åˆ\xa0é™¤",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="ä¸»é¢˜æ–‡æ¡£å…³è\x81”è¡¨",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_comment="ä¸»é¢˜æ–‡æ¡£å…³è\x81”è¡¨",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("uk_topic_document"),
        "pipeline_rag_topic_document_relation",
        ["topic_code", "document_id"],
        unique=True,
    )
    op.create_index(
        op.f("idx_topic_code"), "pipeline_rag_topic_document_relation", ["topic_code"], unique=False
    )
    op.create_index(
        op.f("idx_status"), "pipeline_rag_topic_document_relation", ["status"], unique=False
    )
    op.create_index(
        op.f("idx_document_id"),
        "pipeline_rag_topic_document_relation",
        ["document_id"],
        unique=False,
    )
    op.create_table(
        "pipeline_rag_chat_stage_benchmark",
        sa.Column("id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="ä¸»é”®id"),
        sa.Column(
            "stage_code", mysql.VARCHAR(length=64), nullable=False, comment="é˜¶æ®µç¼–ç\xa0\x81"
        ),
        sa.Column(
            "execution_mode",
            mysql.VARCHAR(length=32),
            nullable=False,
            comment="æ‰§è¡Œæ¨¡å¼\x8fï¼šRAG_CHAT/REACT_AGENT",
        ),
        sa.Column(
            "p50_duration_ms",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="P50è€—æ—¶ï¼ˆæ¯«ç§’ï¼‰",
        ),
        sa.Column(
            "p90_duration_ms",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="P90è€—æ—¶ï¼ˆæ¯«ç§’ï¼‰",
        ),
        sa.Column(
            "p99_duration_ms",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="P99è€—æ—¶ï¼ˆæ¯«ç§’ï¼‰",
        ),
        sa.Column(
            "avg_duration_ms",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="å¹³å\x9d‡è€—æ—¶ï¼ˆæ¯«ç§’ï¼‰",
        ),
        sa.Column(
            "max_duration_ms",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="æœ€å¤§è€—æ—¶ï¼ˆæ¯«ç§’ï¼‰",
        ),
        sa.Column(
            "min_duration_ms",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="æœ€å°\x8fè€—æ—¶ï¼ˆæ¯«ç§’ï¼‰",
        ),
        sa.Column(
            "sample_count",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="æ\xa0·æœ¬æ•°é‡\x8f",
        ),
        sa.Column(
            "recent_durations",
            mysql.JSON(),
            nullable=True,
            comment="æœ€è¿‘Næ¬¡è€—æ—¶è®°å½•ï¼ˆç”¨äºŽæ»‘åŠ¨çª—å\x8f£è®¡ç®—ï¼‰",
        ),
        sa.Column(
            "last_update_time", mysql.DATETIME(), nullable=True, comment="æœ€å\x90Žæ›´æ–°æ—¶é—´"
        ),
        sa.Column("create_time", mysql.DATETIME(), nullable=True, comment="åˆ›å»ºæ—¶é—´"),
        sa.Column("edit_time", mysql.DATETIME(), nullable=True, comment="ç¼–è¾‘æ—¶é—´"),
        sa.Column(
            "status",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=True,
            comment="1:æ\xad£å¸¸ 0:åˆ\xa0é™¤",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="é˜¶æ®µæ€§èƒ½åŸºå‡†è¡¨",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_comment="é˜¶æ®µæ€§èƒ½åŸºå‡†è¡¨",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("uk_stage_benchmark_code_mode"),
        "pipeline_rag_chat_stage_benchmark",
        ["stage_code", "execution_mode"],
        unique=True,
    )
    op.create_table(
        "pipeline_rag_document_parent_block",
        sa.Column("id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="ä¸»é”®id"),
        sa.Column(
            "document_id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="æ–‡æ¡£id"
        ),
        sa.Column(
            "task_id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="ç´¢å¼•ä»»åŠ¡id"
        ),
        sa.Column(
            "plan_id",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="ç\xad–ç•¥æ–¹æ¡ˆid",
        ),
        sa.Column(
            "parent_no",
            mysql.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="çˆ¶å\x9d—åº\x8få\x8f·",
        ),
        sa.Column(
            "source_type",
            mysql.TINYINT(),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=False,
            comment="å†…å®¹æ\x9d¥æº\x90 1:åŽŸæ–‡åˆ‡å\x9d— 2:å\x90Žå¤„ç\x90†è¡¥å…¨æ–‡æœ¬",
        ),
        sa.Column(
            "section_path", mysql.VARCHAR(length=1000), nullable=True, comment="ç«\xa0èŠ‚è·¯å¾„"
        ),
        sa.Column(
            "structure_node_id",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="å…³è\x81”çš„ç»“æž„èŠ‚ç‚¹id",
        ),
        sa.Column(
            "structure_node_type",
            mysql.TINYINT(),
            autoincrement=False,
            nullable=True,
            comment="å…³è\x81”çš„ç»“æž„èŠ‚ç‚¹ç±»åž‹",
        ),
        sa.Column(
            "canonical_path",
            mysql.VARCHAR(length=1000),
            nullable=True,
            comment="ç»“æž„èŠ‚ç‚¹ç¨³å®šè·¯å¾„",
        ),
        sa.Column(
            "item_index",
            mysql.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="åˆ—è¡¨é¡¹/æ\xad¥éª¤é¡¹åº\x8få\x8f·",
        ),
        sa.Column("parent_text", mysql.LONGTEXT(), nullable=True, comment="çˆ¶å\x9d—å®Œæ•´å†…å®¹"),
        sa.Column(
            "char_count",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="å\xad—ç¬¦æ•°",
        ),
        sa.Column(
            "token_count",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="tokenæ•°",
        ),
        sa.Column(
            "child_count",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="çˆ¶å\x9d—å†…éƒ¨childæ•°é‡\x8f",
        ),
        sa.Column(
            "start_chunk_no",
            mysql.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="çˆ¶å\x9d—æ˜\xa0å°„åˆ°çš„ç¬¬ä¸€ä¸ªchildåº\x8få\x8f·",
        ),
        sa.Column(
            "end_chunk_no",
            mysql.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="çˆ¶å\x9d—æ˜\xa0å°„åˆ°çš„æœ€å\x90Žä¸€ä¸ªchildåº\x8få\x8f·",
        ),
        sa.Column("create_time", mysql.DATETIME(), nullable=True, comment="åˆ›å»ºæ—¶é—´"),
        sa.Column("edit_time", mysql.DATETIME(), nullable=True, comment="ç¼–è¾‘æ—¶é—´"),
        sa.Column(
            "status",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=True,
            comment="1:æ\xad£å¸¸ 0:åˆ\xa0é™¤",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="æ–‡æ¡£çˆ¶å\x9d—è¡¨",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_comment="æ–‡æ¡£çˆ¶å\x9d—è¡¨",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("uk_task_parent_no"),
        "pipeline_rag_document_parent_block",
        ["task_id", "parent_no"],
        unique=True,
    )
    op.create_index(
        op.f("idx_task_id"), "pipeline_rag_document_parent_block", ["task_id"], unique=False
    )
    op.create_index(
        op.f("idx_document_id"), "pipeline_rag_document_parent_block", ["document_id"], unique=False
    )
    op.create_table(
        "pipeline_rag_document_task_log",
        sa.Column("id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="ä¸»é”®id"),
        sa.Column(
            "task_id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="ä»»åŠ¡id"
        ),
        sa.Column(
            "document_id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="æ–‡æ¡£id"
        ),
        sa.Column(
            "stage_type",
            mysql.TINYINT(),
            autoincrement=False,
            nullable=False,
            comment="é˜¶æ®µç±»åž‹ 1:æ–‡ä»¶ä¸Šä¼\xa0 2:å†…å®¹è§£æž\x90 3:ç\xad–ç•¥è·¯ç”± 4:ç\xad–ç•¥ç¡®è®¤ 5:åˆ‡å\x9d—æ‰§è¡Œ 6:åˆ‡å\x9d—å\x90Žå¤„ç\x90† 7:å\x90‘é‡\x8fåŒ– 8:å…¥åº“å®Œæˆ\x90",
        ),
        sa.Column(
            "event_type",
            mysql.TINYINT(),
            autoincrement=False,
            nullable=False,
            comment="äº‹ä»¶ç±»åž‹ 1:å¼€å§‹ 2:å®Œæˆ\x90 3:å¤±è´¥ 4:æŽ¨è\x8d\x90ç\xad–ç•¥ 5:ç”¨æˆ·è°ƒæ•´ 6:ç”¨æˆ·ç¡®è®¤",
        ),
        sa.Column(
            "log_level",
            mysql.TINYINT(),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=False,
            comment="æ—¥å¿—çº§åˆ« 1:INFO 2:WARN 3:ERROR",
        ),
        sa.Column(
            "operator_type",
            mysql.TINYINT(),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=False,
            comment="æ“\x8dä½œäººç±»åž‹ 1:ç³»ç»Ÿ 2:ç”¨æˆ· 3:ç®¡ç\x90†å‘˜",
        ),
        sa.Column(
            "operator_id",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="æ“\x8dä½œäººid",
        ),
        sa.Column("content", mysql.VARCHAR(length=1000), nullable=True, comment="æ—¥å¿—å†…å®¹"),
        sa.Column("detail_json", mysql.TEXT(), nullable=True, comment="æ—¥å¿—æ˜Žç»†JSON"),
        sa.Column("create_time", mysql.DATETIME(), nullable=True, comment="åˆ›å»ºæ—¶é—´"),
        sa.Column("edit_time", mysql.DATETIME(), nullable=True, comment="ç¼–è¾‘æ—¶é—´"),
        sa.Column(
            "status",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=True,
            comment="1:æ\xad£å¸¸ 0:åˆ\xa0é™¤",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="æ–‡æ¡£ä»»åŠ¡æ—¥å¿—è¡¨",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_comment="æ–‡æ¡£ä»»åŠ¡æ—¥å¿—è¡¨",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("idx_task_id"), "pipeline_rag_document_task_log", ["task_id"], unique=False
    )
    op.create_index(
        op.f("idx_stage_type"), "pipeline_rag_document_task_log", ["stage_type"], unique=False
    )
    op.create_index(
        op.f("idx_document_id"), "pipeline_rag_document_task_log", ["document_id"], unique=False
    )
    op.create_table(
        "pipeline_rag_chat_channel_execution",
        sa.Column("id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="ä¸»é”®id"),
        sa.Column(
            "dialogue_code",
            mysql.VARCHAR(length=64),
            nullable=False,
            comment="æ‰€å±žä¸šåŠ¡ä¼šè¯\x9dç¼–å\x8f·",
        ),
        sa.Column(
            "exchange_id",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=False,
            comment="æ‰€å±žè½®æ¬¡id",
        ),
        sa.Column(
            "trace_id", mysql.VARCHAR(length=64), nullable=False, comment="æœ¬è½®æ‰§è¡Œtrace id"
        ),
        sa.Column(
            "sub_question_index",
            mysql.INTEGER(),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=False,
            comment="å\xad\x90é—®é¢˜ä¸‹æ\xa0‡ï¼ˆä»Ž1å¼€å§‹ï¼‰",
        ),
        sa.Column("sub_question", mysql.TEXT(), nullable=True, comment="å\xad\x90é—®é¢˜æ–‡æœ¬"),
        sa.Column(
            "channel_type",
            mysql.VARCHAR(length=32),
            nullable=False,
            comment="æ£€ç´¢é€šé\x81“ï¼švector/keyword",
        ),
        sa.Column(
            "execution_state",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=False,
            comment="1:æˆ\x90åŠŸ 2:å¤±è´¥ 3:è¶…æ—¶ 4:è·³è¿‡",
        ),
        sa.Column(
            "start_time",
            mysql.DATETIME(fsp=3),
            nullable=True,
            comment="é€šé\x81“æ‰§è¡Œå¼€å§‹æ—¶é—´ï¼ˆæ¯«ç§’ç²¾åº¦ï¼‰",
        ),
        sa.Column(
            "end_time",
            mysql.DATETIME(fsp=3),
            nullable=True,
            comment="é€šé\x81“æ‰§è¡Œç»“æ\x9dŸæ—¶é—´ï¼ˆæ¯«ç§’ç²¾åº¦ï¼‰",
        ),
        sa.Column(
            "duration_ms",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="é€šé\x81“æ‰§è¡Œè€—æ—¶ï¼Œæ¯«ç§’",
        ),
        sa.Column(
            "recalled_count",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="åŽŸå§‹å\x8f¬å›žæ•°",
        ),
        sa.Column(
            "accepted_count",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="é—¸é—¨å\x90Žä¿\x9dç•™æ•°",
        ),
        sa.Column(
            "final_selected_count",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="æœ€ç»ˆé€‰å…¥Promptæ•°",
        ),
        sa.Column(
            "avg_score",
            mysql.DECIMAL(precision=12, scale=6),
            nullable=True,
            comment="å¹³å\x9d‡åˆ†æ•°",
        ),
        sa.Column(
            "max_score", mysql.DECIMAL(precision=12, scale=6), nullable=True, comment="æœ€é«˜åˆ†æ•°"
        ),
        sa.Column(
            "min_score", mysql.DECIMAL(precision=12, scale=6), nullable=True, comment="æœ€ä½Žåˆ†æ•°"
        ),
        sa.Column(
            "config_snapshot",
            mysql.JSON(),
            nullable=True,
            comment="é€šé\x81“é…\x8dç½®å¿«ç…§ï¼ˆtopKã€\x81é˜ˆå€¼ç\xad‰ï¼‰",
        ),
        sa.Column("error_message", mysql.TEXT(), nullable=True, comment="é”™è¯¯ä¿¡æ\x81¯"),
        sa.Column("create_time", mysql.DATETIME(), nullable=True, comment="åˆ›å»ºæ—¶é—´"),
        sa.Column("edit_time", mysql.DATETIME(), nullable=True, comment="ç¼–è¾‘æ—¶é—´"),
        sa.Column(
            "status",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=True,
            comment="1:æ\xad£å¸¸ 0:åˆ\xa0é™¤",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="æ£€ç´¢é€šé\x81“æ‰§è¡Œè¯¦æƒ…è¡¨",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_comment="æ£€ç´¢é€šé\x81“æ‰§è¡Œè¯¦æƒ…è¡¨",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("idx_channel_exec_trace"),
        "pipeline_rag_chat_channel_execution",
        ["trace_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_channel_exec_exchange"),
        "pipeline_rag_chat_channel_execution",
        ["dialogue_code", "exchange_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_channel_exec_channel"),
        "pipeline_rag_chat_channel_execution",
        ["channel_type", "execution_state"],
        unique=False,
    )
    op.create_table(
        "pipeline_rag_chat_exchange",
        sa.Column("id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="ä¸»é”®id"),
        sa.Column(
            "dialogue_code",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=64),
            nullable=False,
            comment="æ‰€å±žä¸šåŠ¡ä¼šè¯\x9dç¼–å\x8f·",
        ),
        sa.Column(
            "user_prompt",
            mysql.TEXT(collation="utf8mb4_unicode_ci"),
            nullable=False,
            comment="ç”¨æˆ·æ\x8f\x90é—®",
        ),
        sa.Column(
            "reply_content",
            mysql.LONGTEXT(collation="utf8mb4_unicode_ci"),
            nullable=False,
            comment="åŠ©æ‰‹å›žç\xad”å†…å®¹",
        ),
        sa.Column(
            "reasoning_note_list",
            mysql.JSON(),
            nullable=False,
            comment="è¿‡ç¨‹æ\x8f\x90ç¤ºä¸Žæ€\x9dè€ƒç‰‡æ®µ",
        ),
        sa.Column(
            "source_snapshot_list", mysql.JSON(), nullable=False, comment="å¼•ç”¨æ\x9d¥æº\x90å¿«ç…§"
        ),
        sa.Column(
            "followup_suggestion_list",
            mysql.JSON(),
            nullable=False,
            comment="æŽ¨è\x8d\x90è¿½é—®å¿«ç…§",
        ),
        sa.Column(
            "tool_trace_list", mysql.JSON(), nullable=False, comment="å·¥å…·ä½¿ç”¨è½¨è¿¹å¿«ç…§"
        ),
        sa.Column("debug_trace_json", mysql.JSON(), nullable=True, comment="è°ƒè¯•è½¨è¿¹å¿«ç…§"),
        sa.Column(
            "exchange_state",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=False,
            comment="1:è¿›è¡Œä¸\xad 2:å·²å®Œæˆ\x90 3:å¤±è´¥ 4:å·²å\x81œæ\xad¢",
        ),
        sa.Column(
            "finish_note",
            mysql.TEXT(collation="utf8mb4_unicode_ci"),
            nullable=True,
            comment="å¤±è´¥æˆ–ç»ˆæ\xad¢è¯´æ˜Ž",
        ),
        sa.Column(
            "first_token_latency_ms",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="é¦–åŒ…è€—æ—¶ï¼Œæ¯«ç§’",
        ),
        sa.Column(
            "total_latency_ms",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="æ€»è€—æ—¶ï¼Œæ¯«ç§’",
        ),
        sa.Column("create_time", mysql.DATETIME(), nullable=True, comment="åˆ›å»ºæ—¶é—´"),
        sa.Column("edit_time", mysql.DATETIME(), nullable=True, comment="ç¼–è¾‘æ—¶é—´"),
        sa.Column(
            "status",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=True,
            comment="1:æ\xad£å¸¸ 0:åˆ\xa0é™¤",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="ä¸šåŠ¡å¯¹è¯\x9dè½®æ¬¡å½’æ¡£è¡¨",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_comment="ä¸šåŠ¡å¯¹è¯\x9dè½®æ¬¡å½’æ¡£è¡¨",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("idx_pipeline_rag_chat_exchange_state_status"),
        "pipeline_rag_chat_exchange",
        ["exchange_state", "status"],
        unique=False,
    )
    op.create_index(
        op.f("idx_pipeline_rag_chat_exchange_dialogue_status"),
        "pipeline_rag_chat_exchange",
        ["dialogue_code", "status"],
        unique=False,
    )
    op.create_index(
        op.f("idx_pipeline_rag_chat_exchange_create_time"),
        "pipeline_rag_chat_exchange",
        ["create_time"],
        unique=False,
    )
    op.create_table(
        "pipeline_rag_document_strategy_step",
        sa.Column("id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="ä¸»é”®id"),
        sa.Column(
            "plan_id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="æ–¹æ¡ˆid"
        ),
        sa.Column(
            "document_id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="æ–‡æ¡£id"
        ),
        sa.Column(
            "step_no",
            mysql.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="æ‰§è¡Œé¡ºåº\x8f",
        ),
        sa.Column(
            "pipeline_type",
            mysql.VARCHAR(length=16),
            nullable=False,
            comment="æµ\x81æ°´çº¿ç±»åž‹ PARENT:çˆ¶å\x9d—æµ\x81æ°´çº¿ CHILD:å\xad\x90å\x9d—æµ\x81æ°´çº¿",
        ),
        sa.Column(
            "strategy_type",
            mysql.TINYINT(),
            autoincrement=False,
            nullable=False,
            comment="ç\xad–ç•¥ç±»åž‹ 1:åŸºäºŽæ–‡æ¡£ç»“æž„åˆ‡å\x9d— 2:é€’å½’åˆ†å\x9d— 3:è¯\xadä¹‰åˆ†å\x9d— 4:å¤§æ¨¡åž‹æ™ºèƒ½åˆ‡å\x9d—",
        ),
        sa.Column(
            "strategy_role",
            mysql.TINYINT(),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=False,
            comment="ç\xad–ç•¥è§’è‰² 1:ä¸»ç\xad–ç•¥ 2:ä¼˜åŒ–ç\xad–ç•¥ 3:å…œåº•ç\xad–ç•¥ 4:å¢žå¼ºç\xad–ç•¥",
        ),
        sa.Column(
            "source_type",
            mysql.TINYINT(),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=False,
            comment="æ\x9d¥æº\x90ç±»åž‹ 1:ç³»ç»ŸæŽ¨è\x8d\x90 2:ç”¨æˆ·æ–°å¢ž 3:ç”¨æˆ·ä¿\x9dç•™",
        ),
        sa.Column(
            "execute_status",
            mysql.TINYINT(),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=False,
            comment="æ‰§è¡ŒçŠ¶æ€\x81 1:å¾…æ‰§è¡Œ 2:æ‰§è¡Œä¸\xad 3:æ‰§è¡Œæˆ\x90åŠŸ 4:æ‰§è¡Œå¤±è´¥ 5:å·²è·³è¿‡",
        ),
        sa.Column(
            "recommend_reason",
            mysql.VARCHAR(length=500),
            nullable=True,
            comment="æœ¬æ\xad¥éª¤æŽ¨è\x8d\x90åŽŸå›\xa0",
        ),
        sa.Column("create_time", mysql.DATETIME(), nullable=True, comment="åˆ›å»ºæ—¶é—´"),
        sa.Column("edit_time", mysql.DATETIME(), nullable=True, comment="ç¼–è¾‘æ—¶é—´"),
        sa.Column(
            "status",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=True,
            comment="1:æ\xad£å¸¸ 0:åˆ\xa0é™¤",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="æ–‡æ¡£ç\xad–ç•¥æ\xad¥éª¤è¡¨",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_comment="æ–‡æ¡£ç\xad–ç•¥æ\xad¥éª¤è¡¨",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("uk_plan_pipeline_step_no"),
        "pipeline_rag_document_strategy_step",
        ["plan_id", "pipeline_type", "step_no"],
        unique=True,
    )
    op.create_index(
        op.f("idx_strategy_type"),
        "pipeline_rag_document_strategy_step",
        ["strategy_type"],
        unique=False,
    )
    op.create_index(
        op.f("idx_pipeline_type"),
        "pipeline_rag_document_strategy_step",
        ["pipeline_type"],
        unique=False,
    )
    op.create_index(
        op.f("idx_document_id"),
        "pipeline_rag_document_strategy_step",
        ["document_id"],
        unique=False,
    )
    op.create_table(
        "pipeline_rag_document_chunk",
        sa.Column("id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="ä¸»é”®id"),
        sa.Column(
            "document_id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="æ–‡æ¡£id"
        ),
        sa.Column(
            "task_id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="ç´¢å¼•ä»»åŠ¡id"
        ),
        sa.Column(
            "plan_id",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="ç\xad–ç•¥æ–¹æ¡ˆid",
        ),
        sa.Column(
            "parent_block_id",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=False,
            comment="æ‰€å±žçˆ¶å\x9d—id",
        ),
        sa.Column(
            "chunk_no",
            mysql.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="å\x9d—åº\x8få\x8f·",
        ),
        sa.Column(
            "source_type",
            mysql.TINYINT(),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=False,
            comment="å†…å®¹æ\x9d¥æº\x90 1:åŽŸæ–‡åˆ‡å\x9d— 2:å\x90Žå¤„ç\x90†è¡¥å…¨æ–‡æœ¬",
        ),
        sa.Column(
            "section_path", mysql.VARCHAR(length=1000), nullable=True, comment="ç«\xa0èŠ‚è·¯å¾„"
        ),
        sa.Column(
            "structure_node_id",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="å…³è\x81”çš„ç»“æž„èŠ‚ç‚¹id",
        ),
        sa.Column(
            "structure_node_type",
            mysql.TINYINT(),
            autoincrement=False,
            nullable=True,
            comment="å…³è\x81”çš„ç»“æž„èŠ‚ç‚¹ç±»åž‹",
        ),
        sa.Column(
            "canonical_path",
            mysql.VARCHAR(length=1000),
            nullable=True,
            comment="ç»“æž„èŠ‚ç‚¹ç¨³å®šè·¯å¾„",
        ),
        sa.Column(
            "item_index",
            mysql.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="åˆ—è¡¨é¡¹/æ\xad¥éª¤é¡¹åº\x8få\x8f·",
        ),
        sa.Column("chunk_text", mysql.LONGTEXT(), nullable=True, comment="åˆ‡å\x9d—å†…å®¹"),
        sa.Column(
            "char_count",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="å\xad—ç¬¦æ•°",
        ),
        sa.Column(
            "token_count",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="tokenæ•°",
        ),
        sa.Column(
            "vector_status",
            mysql.TINYINT(),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=False,
            comment="å\x90‘é‡\x8fçŠ¶æ€\x81 1:å¾…å\x90‘é‡\x8fåŒ– 2:å\x90‘é‡\x8fåŒ–ä¸\xad 3:å\x90‘é‡\x8fåŒ–æˆ\x90åŠŸ 4:å\x90‘é‡\x8fåŒ–å¤±è´¥",
        ),
        sa.Column(
            "vector_store_type",
            mysql.TINYINT(),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=False,
            comment="å\x90‘é‡\x8fåº“ç±»åž‹ 1:Milvus 2:PGVector 3:Elasticsearch",
        ),
        sa.Column(
            "vector_id", mysql.VARCHAR(length=128), nullable=True, comment="å\x90‘é‡\x8fåº“ä¸»é”®"
        ),
        sa.Column("create_time", mysql.DATETIME(), nullable=True, comment="åˆ›å»ºæ—¶é—´"),
        sa.Column("edit_time", mysql.DATETIME(), nullable=True, comment="ç¼–è¾‘æ—¶é—´"),
        sa.Column(
            "status",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=True,
            comment="1:æ\xad£å¸¸ 0:åˆ\xa0é™¤",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="æ–‡æ¡£åˆ‡å\x9d—è¡¨",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_comment="æ–‡æ¡£åˆ‡å\x9d—è¡¨",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("uk_task_chunk_no"),
        "pipeline_rag_document_chunk",
        ["task_id", "chunk_no"],
        unique=True,
    )
    op.create_index(
        op.f("idx_vector_status"), "pipeline_rag_document_chunk", ["vector_status"], unique=False
    )
    op.create_index(
        op.f("idx_parent_block_id"),
        "pipeline_rag_document_chunk",
        ["parent_block_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_document_id"), "pipeline_rag_document_chunk", ["document_id"], unique=False
    )
    op.create_table(
        "GRAPH_CHECKPOINT",
        sa.Column(
            "checkpoint_id",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=36),
            nullable=False,
            comment="Checkpoint ID",
        ),
        sa.Column(
            "thread_id",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=36),
            nullable=False,
            comment="å…³è\x81”çº¿ç¨‹ID",
        ),
        sa.Column(
            "node_id",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=255),
            nullable=True,
            comment="å½“å‰\x8dèŠ‚ç‚¹ID",
        ),
        sa.Column(
            "next_node_id",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=255),
            nullable=True,
            comment="ä¸‹ä¸€ä¸ªèŠ‚ç‚¹ID",
        ),
        sa.Column(
            "state_data",
            mysql.JSON(),
            nullable=False,
            comment="åº\x8fåˆ—åŒ–å\x90Žçš„ Agent çŠ¶æ€\x81",
        ),
        sa.Column(
            "saved_at",
            mysql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="ä¿\x9då\xad˜æ—¶é—´",
        ),
        sa.PrimaryKeyConstraint("checkpoint_id"),
        comment="Spring AI Alibaba Graph checkpoint è¡¨",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_comment="Spring AI Alibaba Graph checkpoint è¡¨",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("idx_graph_checkpoint_thread_saved"),
        "GRAPH_CHECKPOINT",
        ["thread_id", "saved_at"],
        unique=False,
    )
    op.create_table(
        "pipeline_rag_knowledge_topic_node",
        sa.Column("id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="ä¸»é”®id"),
        sa.Column(
            "topic_code", mysql.VARCHAR(length=64), nullable=False, comment="ä¸»é¢˜ç¼–ç\xa0\x81"
        ),
        sa.Column(
            "topic_name", mysql.VARCHAR(length=128), nullable=False, comment="ä¸»é¢˜å\x90\x8dç§°"
        ),
        sa.Column(
            "scope_code",
            mysql.VARCHAR(length=64),
            nullable=False,
            comment="æ‰€å±žçŸ¥è¯†èŒƒå›´ç¼–ç\xa0\x81",
        ),
        sa.Column(
            "description", mysql.VARCHAR(length=1024), nullable=True, comment="ä¸»é¢˜æ\x8f\x8fè¿°"
        ),
        sa.Column(
            "aliases",
            mysql.VARCHAR(length=512),
            nullable=True,
            comment="åˆ«å\x90\x8dï¼Œè‹±æ–‡é€—å\x8f·åˆ†éš”",
        ),
        sa.Column("examples", mysql.TEXT(), nullable=True, comment="å…¸åž‹é—®é¢˜ JSON æ•°ç»„"),
        sa.Column(
            "answer_shape",
            mysql.VARCHAR(length=64),
            nullable=True,
            comment="å»ºè®®å›žç\xad”å½¢æ€\x81 explain/list/steps/compare/structure",
        ),
        sa.Column(
            "execution_preference",
            mysql.VARCHAR(length=64),
            nullable=True,
            comment="æ‰§è¡Œå\x81\x8få¥½ retrieval/graph_only/graph_then_evidence/graph_assist",
        ),
        sa.Column(
            "sort_order",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="æŽ’åº\x8få€¼",
        ),
        sa.Column("create_time", mysql.DATETIME(), nullable=True, comment="åˆ›å»ºæ—¶é—´"),
        sa.Column("edit_time", mysql.DATETIME(), nullable=True, comment="ç¼–è¾‘æ—¶é—´"),
        sa.Column(
            "status",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=True,
            comment="1:æ\xad£å¸¸ 0:åˆ\xa0é™¤",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="çŸ¥è¯†ä¸»é¢˜èŠ‚ç‚¹è¡¨",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_comment="çŸ¥è¯†ä¸»é¢˜èŠ‚ç‚¹è¡¨",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("uk_topic_code"), "pipeline_rag_knowledge_topic_node", ["topic_code"], unique=True
    )
    op.create_index(
        op.f("idx_status"), "pipeline_rag_knowledge_topic_node", ["status"], unique=False
    )
    op.create_index(
        op.f("idx_scope_code"), "pipeline_rag_knowledge_topic_node", ["scope_code"], unique=False
    )
    op.create_table(
        "pipeline_rag_knowledge_scope_node",
        sa.Column("id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="ä¸»é”®id"),
        sa.Column(
            "scope_code",
            mysql.VARCHAR(length=64),
            nullable=False,
            comment="çŸ¥è¯†èŒƒå›´ç¼–ç\xa0\x81",
        ),
        sa.Column(
            "scope_name",
            mysql.VARCHAR(length=128),
            nullable=False,
            comment="çŸ¥è¯†èŒƒå›´å\x90\x8dç§°",
        ),
        sa.Column(
            "parent_scope_code",
            mysql.VARCHAR(length=64),
            nullable=True,
            comment="çˆ¶çº§çŸ¥è¯†èŒƒå›´ç¼–ç\xa0\x81",
        ),
        sa.Column(
            "description", mysql.VARCHAR(length=1024), nullable=True, comment="èŒƒå›´æ\x8f\x8fè¿°"
        ),
        sa.Column(
            "aliases",
            mysql.VARCHAR(length=512),
            nullable=True,
            comment="åˆ«å\x90\x8dï¼Œè‹±æ–‡é€—å\x8f·åˆ†éš”",
        ),
        sa.Column("examples", mysql.TEXT(), nullable=True, comment="å…¸åž‹é—®é¢˜ JSON æ•°ç»„"),
        sa.Column(
            "sort_order",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="æŽ’åº\x8få€¼",
        ),
        sa.Column("create_time", mysql.DATETIME(), nullable=True, comment="åˆ›å»ºæ—¶é—´"),
        sa.Column("edit_time", mysql.DATETIME(), nullable=True, comment="ç¼–è¾‘æ—¶é—´"),
        sa.Column(
            "status",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=True,
            comment="1:æ\xad£å¸¸ 0:åˆ\xa0é™¤",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="çŸ¥è¯†èŒƒå›´èŠ‚ç‚¹è¡¨",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_comment="çŸ¥è¯†èŒƒå›´èŠ‚ç‚¹è¡¨",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("uk_scope_code"), "pipeline_rag_knowledge_scope_node", ["scope_code"], unique=True
    )
    op.create_index(
        op.f("idx_status"), "pipeline_rag_knowledge_scope_node", ["status"], unique=False
    )
    op.create_index(
        op.f("idx_parent_scope_code"),
        "pipeline_rag_knowledge_scope_node",
        ["parent_scope_code"],
        unique=False,
    )
    op.create_table(
        "pipeline_rag_chat_retrieval_result",
        sa.Column("id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="ä¸»é”®id"),
        sa.Column(
            "dialogue_code",
            mysql.VARCHAR(length=64),
            nullable=False,
            comment="æ‰€å±žä¸šåŠ¡ä¼šè¯\x9dç¼–å\x8f·",
        ),
        sa.Column(
            "exchange_id",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=False,
            comment="æ‰€å±žè½®æ¬¡id",
        ),
        sa.Column(
            "trace_id", mysql.VARCHAR(length=64), nullable=False, comment="æœ¬è½®æ‰§è¡Œtrace id"
        ),
        sa.Column(
            "sub_question_index",
            mysql.INTEGER(),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=False,
            comment="å\xad\x90é—®é¢˜ä¸‹æ\xa0‡ï¼ˆä»Ž1å¼€å§‹ï¼‰",
        ),
        sa.Column("sub_question", mysql.TEXT(), nullable=True, comment="å\xad\x90é—®é¢˜æ–‡æœ¬"),
        sa.Column(
            "channel_type",
            mysql.VARCHAR(length=32),
            nullable=False,
            comment="æ£€ç´¢é€šé\x81“ï¼švector/keyword/hybrid",
        ),
        sa.Column(
            "channel_rank",
            mysql.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="é€šé\x81“å†…åŽŸå§‹æŽ’å\x90\x8d",
        ),
        sa.Column(
            "rrf_rank",
            mysql.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="RRFèž\x8då\x90ˆå\x90ŽæŽ’å\x90\x8d",
        ),
        sa.Column(
            "final_rank",
            mysql.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="æœ€ç»ˆæŽ’å\x90\x8dï¼ˆrerankå\x90Žæˆ–æœ€ç»ˆè£\x81å‰ªå\x90Žï¼‰",
        ),
        sa.Column(
            "original_score",
            mysql.DECIMAL(precision=12, scale=6),
            nullable=True,
            comment="é€šé\x81“åŽŸå§‹åˆ†æ•°",
        ),
        sa.Column(
            "rrf_score",
            mysql.DECIMAL(precision=12, scale=6),
            nullable=True,
            comment="RRFèž\x8då\x90ˆåˆ†æ•°",
        ),
        sa.Column(
            "rerank_score",
            mysql.DECIMAL(precision=12, scale=6),
            nullable=True,
            comment="Rerankç²¾æŽ’åˆ†æ•°",
        ),
        sa.Column(
            "gate_passed",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=True,
            comment="æ˜¯å\x90¦é€šè¿‡ç›¸å…³æ€§é—¸é—¨ï¼š1æ˜¯ 0å\x90¦",
        ),
        sa.Column(
            "is_elevated",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="æ˜¯å\x90¦æ\x8f\x90å\x8d‡åˆ°çˆ¶å\x9d—ï¼š1æ˜¯ 0å\x90¦",
        ),
        sa.Column(
            "is_selected",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="æ˜¯å\x90¦è¢«é€‰å…¥æœ€ç»ˆPromptï¼š1æ˜¯ 0å\x90¦",
        ),
        sa.Column(
            "selection_reason",
            mysql.VARCHAR(length=255),
            nullable=True,
            comment="é€‰å…¥/æŽ’é™¤åŽŸå›\xa0",
        ),
        sa.Column(
            "document_id", mysql.BIGINT(), autoincrement=False, nullable=True, comment="æ–‡æ¡£id"
        ),
        sa.Column(
            "document_name", mysql.VARCHAR(length=255), nullable=True, comment="æ–‡æ¡£å\x90\x8dç§°"
        ),
        sa.Column(
            "chunk_id",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="æ–‡æ¡£åˆ‡å\x9d—id",
        ),
        sa.Column(
            "chunk_no",
            mysql.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="åˆ‡å\x9d—åº\x8få\x8f·",
        ),
        sa.Column(
            "parent_block_id",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="çˆ¶å\x9d—id",
        ),
        sa.Column(
            "parent_block_no",
            mysql.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="çˆ¶å\x9d—åº\x8få\x8f·",
        ),
        sa.Column(
            "section_path", mysql.VARCHAR(length=512), nullable=True, comment="ç«\xa0èŠ‚è·¯å¾„"
        ),
        sa.Column(
            "chunk_text_preview",
            mysql.VARCHAR(length=500),
            nullable=True,
            comment="æ–‡æ¡£å\x9d—å†…å®¹é¢„è§ˆï¼ˆå‰\x8d500å\xad—ç¬¦ï¼‰",
        ),
        sa.Column(
            "chunk_char_count",
            mysql.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="æ–‡æ¡£å\x9d—å\xad—ç¬¦æ•°",
        ),
        sa.Column("create_time", mysql.DATETIME(), nullable=True, comment="åˆ›å»ºæ—¶é—´"),
        sa.Column("edit_time", mysql.DATETIME(), nullable=True, comment="ç¼–è¾‘æ—¶é—´"),
        sa.Column(
            "status",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=True,
            comment="1:æ\xad£å¸¸ 0:åˆ\xa0é™¤",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="æ£€ç´¢ç»“æžœå¿«ç…§è¡¨",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_comment="æ£€ç´¢ç»“æžœå¿«ç…§è¡¨",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("idx_retrieval_result_trace"),
        "pipeline_rag_chat_retrieval_result",
        ["trace_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_retrieval_result_sub_question"),
        "pipeline_rag_chat_retrieval_result",
        ["exchange_id", "sub_question_index"],
        unique=False,
    )
    op.create_index(
        op.f("idx_retrieval_result_exchange"),
        "pipeline_rag_chat_retrieval_result",
        ["dialogue_code", "exchange_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_retrieval_result_document"),
        "pipeline_rag_chat_retrieval_result",
        ["document_id", "chunk_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_retrieval_result_channel"),
        "pipeline_rag_chat_retrieval_result",
        ["channel_type", "is_selected"],
        unique=False,
    )
    op.create_table(
        "pipeline_rag_chat_dialogue",
        sa.Column("id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="ä¸»é”®id"),
        sa.Column(
            "dialogue_code",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=64),
            nullable=False,
            comment="ä¸šåŠ¡ä¼šè¯\x9dç¼–å\x8f·",
        ),
        sa.Column(
            "dialogue_stage",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=False,
            comment="1:ç©ºé—² 2:è¿›è¡Œä¸\xad",
        ),
        sa.Column(
            "chat_mode",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=False,
            comment="1:å½“å‰\x8dæ–‡æ¡£é—®ç\xad” 2:å¼€æ”¾å¼\x8fæ\x8f\x90é—®",
        ),
        sa.Column(
            "selected_document_id",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="å½“å‰\x8dä¼šè¯\x9dæ˜¾å¼\x8fé”\x81å®šçš„æ\x8f\x90é—®æ–‡æ¡£id",
        ),
        sa.Column(
            "selected_document_name",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=255),
            nullable=True,
            comment="å½“å‰\x8dä¼šè¯\x9dæ˜¾å¼\x8fé”\x81å®šçš„æ\x8f\x90é—®æ–‡æ¡£å\x90\x8dç§°",
        ),
        sa.Column("create_time", mysql.DATETIME(), nullable=True, comment="åˆ›å»ºæ—¶é—´"),
        sa.Column("edit_time", mysql.DATETIME(), nullable=True, comment="ç¼–è¾‘æ—¶é—´"),
        sa.Column(
            "status",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=True,
            comment="1:æ\xad£å¸¸ 0:åˆ\xa0é™¤",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="ä¸šåŠ¡å¯¹è¯\x9då½’æ¡£ä¸»è¡¨",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_comment="ä¸šåŠ¡å¯¹è¯\x9då½’æ¡£ä¸»è¡¨",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("idx_pipeline_rag_chat_dialogue_stage_status"),
        "pipeline_rag_chat_dialogue",
        ["dialogue_stage", "status"],
        unique=False,
    )
    op.create_index(
        op.f("idx_pipeline_rag_chat_dialogue_edit_time"),
        "pipeline_rag_chat_dialogue",
        ["edit_time"],
        unique=False,
    )
    op.create_index(
        op.f("idx_pipeline_rag_chat_dialogue_code_status"),
        "pipeline_rag_chat_dialogue",
        ["dialogue_code", "status"],
        unique=False,
    )
    op.create_table(
        "pipeline_rag_document_profile",
        sa.Column("id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="ä¸»é”®id"),
        sa.Column(
            "document_id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="æ–‡æ¡£id"
        ),
        sa.Column(
            "profile_version",
            mysql.INTEGER(),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=True,
            comment="ç”»åƒ\x8fç‰ˆæœ¬",
        ),
        sa.Column("document_summary", mysql.TEXT(), nullable=True, comment="æ–‡æ¡£æ‘˜è¦\x81"),
        sa.Column(
            "document_type",
            mysql.VARCHAR(length=64),
            nullable=True,
            comment="æ–‡æ¡£ç±»åž‹ intro/manual/rule/faq/troubleshooting/spec",
        ),
        sa.Column(
            "core_topics", mysql.TEXT(), nullable=True, comment="æ\xa0¸å¿ƒä¸»é¢˜ JSON æ•°ç»„"
        ),
        sa.Column(
            "example_questions", mysql.TEXT(), nullable=True, comment="å…¸åž‹é—®é¢˜ JSON æ•°ç»„"
        ),
        sa.Column(
            "graph_friendly",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="æ˜¯å\x90¦é€‚å\x90ˆå›¾ç»“æž„é—®ç\xad” 1:æ˜¯ 0:å\x90¦",
        ),
        sa.Column(
            "supports_graph_outline",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="æ˜¯å\x90¦æ”¯æŒ\x81ç«\xa0èŠ‚åˆ—è¡¨/ç›®å½•ç±»å›¾å›žç\xad”",
        ),
        sa.Column(
            "supports_item_lookup",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="æ˜¯å\x90¦æ”¯æŒ\x81æ\xad¥éª¤/item æŸ¥è¯¢",
        ),
        sa.Column(
            "supports_graph_assist",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
            comment="æ˜¯å\x90¦æ”¯æŒ\x81å›¾è¾…åŠ©æ£€ç´¢",
        ),
        sa.Column(
            "profile_source",
            mysql.VARCHAR(length=64),
            nullable=True,
            comment="ç”»åƒ\x8fæ\x9d¥æº\x90 auto/manual/mixed",
        ),
        sa.Column(
            "profile_status",
            mysql.TINYINT(),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=True,
            comment="ç”»åƒ\x8fçŠ¶æ€\x81 1:å¾…ç”Ÿæˆ\x90 2:ç”Ÿæˆ\x90æˆ\x90åŠŸ 3:ç”Ÿæˆ\x90å¤±è´¥ 4:äººå·¥ç¡®è®¤",
        ),
        sa.Column(
            "error_msg",
            mysql.VARCHAR(length=1024),
            nullable=True,
            comment="ç”»åƒ\x8få¤±è´¥åŽŸå›\xa0",
        ),
        sa.Column("create_time", mysql.DATETIME(), nullable=True, comment="åˆ›å»ºæ—¶é—´"),
        sa.Column("edit_time", mysql.DATETIME(), nullable=True, comment="ç¼–è¾‘æ—¶é—´"),
        sa.Column(
            "status",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=True,
            comment="1:æ\xad£å¸¸ 0:åˆ\xa0é™¤",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="æ–‡æ¡£ç”»åƒ\x8fè¡¨",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_comment="æ–‡æ¡£ç”»åƒ\x8fè¡¨",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("uk_document_id"), "pipeline_rag_document_profile", ["document_id"], unique=True
    )
    op.create_index(op.f("idx_status"), "pipeline_rag_document_profile", ["status"], unique=False)
    op.create_index(
        op.f("idx_profile_status"),
        "pipeline_rag_document_profile",
        ["profile_status"],
        unique=False,
    )
    op.create_index(
        op.f("idx_document_type"), "pipeline_rag_document_profile", ["document_type"], unique=False
    )
    op.create_table(
        "pipeline_rag_chat_exchange_trace_stage",
        sa.Column("id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="ä¸»é”®id"),
        sa.Column(
            "dialogue_code",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=64),
            nullable=False,
            comment="æ‰€å±žä¸šåŠ¡ä¼šè¯\x9dç¼–å\x8f·",
        ),
        sa.Column(
            "exchange_id",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=False,
            comment="æ‰€å±žè½®æ¬¡id",
        ),
        sa.Column(
            "trace_id",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=64),
            nullable=False,
            comment="æœ¬è½®æ‰§è¡Œtrace id",
        ),
        sa.Column(
            "stage_code",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=64),
            nullable=False,
            comment="é˜¶æ®µç¼–ç\xa0\x81",
        ),
        sa.Column(
            "stage_name",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=128),
            nullable=False,
            comment="é˜¶æ®µå\x90\x8dç§°",
        ),
        sa.Column(
            "stage_order",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
            comment="é˜¶æ®µé¡ºåº\x8f",
        ),
        sa.Column(
            "stage_level",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=False,
            comment="1:ä¸€çº§é˜¶æ®µ 2:äºŒçº§å\xad\x90æ\xad¥éª¤",
        ),
        sa.Column(
            "parent_stage_id",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="çˆ¶é˜¶æ®µid",
        ),
        sa.Column(
            "execution_mode",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=32),
            nullable=True,
            comment="æ‰§è¡Œæ¨¡å¼\x8f",
        ),
        sa.Column(
            "stage_state",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=False,
            comment="1:è¿\x90è¡Œä¸\xad 2:å®Œæˆ\x90 3:å¤±è´¥ 4:è·³è¿‡",
        ),
        sa.Column("start_time", mysql.DATETIME(), nullable=True, comment="é˜¶æ®µå¼€å§‹æ—¶é—´"),
        sa.Column("end_time", mysql.DATETIME(), nullable=True, comment="é˜¶æ®µç»“æ\x9dŸæ—¶é—´"),
        sa.Column(
            "duration_ms",
            mysql.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="é˜¶æ®µè€—æ—¶ï¼Œæ¯«ç§’",
        ),
        sa.Column(
            "summary_text",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=1000),
            nullable=True,
            comment="é˜¶æ®µæ‘˜è¦\x81",
        ),
        sa.Column(
            "error_message",
            mysql.TEXT(collation="utf8mb4_unicode_ci"),
            nullable=True,
            comment="é˜¶æ®µé”™è¯¯ä¿¡æ\x81¯",
        ),
        sa.Column("snapshot_json", mysql.JSON(), nullable=True, comment="é˜¶æ®µç»“æž„åŒ–å¿«ç…§"),
        sa.Column("create_time", mysql.DATETIME(), nullable=True, comment="åˆ›å»ºæ—¶é—´"),
        sa.Column("edit_time", mysql.DATETIME(), nullable=True, comment="ç¼–è¾‘æ—¶é—´"),
        sa.Column(
            "status",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=True,
            comment="1:æ\xad£å¸¸ 0:åˆ\xa0é™¤",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="å¯¹è¯\x9dè½®æ¬¡æ‰§è¡Œé˜¶æ®µè½¨è¿¹è¡¨",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_comment="å¯¹è¯\x9dè½®æ¬¡æ‰§è¡Œé˜¶æ®µè½¨è¿¹è¡¨",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("idx_pipeline_rag_chat_trace_trace_id"),
        "pipeline_rag_chat_exchange_trace_stage",
        ["trace_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_pipeline_rag_chat_trace_stage_code"),
        "pipeline_rag_chat_exchange_trace_stage",
        ["stage_code"],
        unique=False,
    )
    op.create_index(
        op.f("idx_pipeline_rag_chat_trace_exchange"),
        "pipeline_rag_chat_exchange_trace_stage",
        ["exchange_id", "stage_order"],
        unique=False,
    )
    op.create_index(
        op.f("idx_pipeline_rag_chat_trace_dialogue"),
        "pipeline_rag_chat_exchange_trace_stage",
        ["dialogue_code", "exchange_id"],
        unique=False,
    )
    op.create_table(
        "pipeline_rag_chat_memory_summary",
        sa.Column("id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="ä¸»é”®id"),
        sa.Column(
            "dialogue_code",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=64),
            nullable=False,
            comment="æ‰€å±žä¸šåŠ¡ä¼šè¯\x9dç¼–å\x8f·",
        ),
        sa.Column(
            "covered_exchange_id",
            mysql.BIGINT(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
            comment="é•¿æœŸæ‘˜è¦\x81å·²è¦†ç›–åˆ°çš„æœ€å\x90Žä¸€æ\x9d¡exchangeId",
        ),
        sa.Column(
            "covered_exchange_count",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
            comment="é•¿æœŸæ‘˜è¦\x81å·²è¦†ç›–çš„è½®æ¬¡æ•°",
        ),
        sa.Column(
            "compression_count",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
            comment="ç´¯è®¡åŽ‹ç¼©æ¬¡æ•°",
        ),
        sa.Column(
            "summary_version",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
            comment="æ‘˜è¦\x81ç‰ˆæœ¬å\x8f·",
        ),
        sa.Column(
            "summary_text",
            mysql.LONGTEXT(collation="utf8mb4_unicode_ci"),
            nullable=False,
            comment="ç¼–æŽ’é˜¶æ®µç›´æŽ¥ä½¿ç”¨çš„é•¿æœŸæ‘˜è¦\x81æ–‡æœ¬",
        ),
        sa.Column(
            "summary_json", mysql.JSON(), nullable=True, comment="é•¿æœŸæ‘˜è¦\x81ç»“æž„åŒ–JSON"
        ),
        sa.Column(
            "last_source_edit_time",
            mysql.DATETIME(),
            nullable=True,
            comment="æ‘˜è¦\x81è¦†ç›–æº\x90è½®æ¬¡çš„æœ€å\x90Žæ›´æ–°æ—¶é—´",
        ),
        sa.Column("create_time", mysql.DATETIME(), nullable=True, comment="åˆ›å»ºæ—¶é—´"),
        sa.Column("edit_time", mysql.DATETIME(), nullable=True, comment="ç¼–è¾‘æ—¶é—´"),
        sa.Column(
            "status",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=True,
            comment="1:æ\xad£å¸¸ 0:åˆ\xa0é™¤",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="ä¸šåŠ¡å¯¹è¯\x9dé•¿æœŸè®°å¿†æ‘˜è¦\x81å¿«ç…§è¡¨",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_comment="ä¸šåŠ¡å¯¹è¯\x9dé•¿æœŸè®°å¿†æ‘˜è¦\x81å¿«ç…§è¡¨",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("uk_pipeline_rag_chat_memory_summary_dialogue"),
        "pipeline_rag_chat_memory_summary",
        ["dialogue_code"],
        unique=True,
    )
    op.create_index(
        op.f("idx_pipeline_rag_chat_memory_summary_edit_time"),
        "pipeline_rag_chat_memory_summary",
        ["edit_time"],
        unique=False,
    )
    op.create_index(
        op.f("idx_pipeline_rag_chat_memory_summary_cover"),
        "pipeline_rag_chat_memory_summary",
        ["covered_exchange_id"],
        unique=False,
    )
    op.drop_table("document_task")
    op.drop_table("document_chunk")
    op.drop_table("document")
    op.drop_table("knowledge_topic")
    op.drop_index(
        op.f("ix_conversation_exchange_conversation_id"), table_name="conversation_exchange"
    )
    op.drop_table("conversation_exchange")
    op.drop_index(
        op.f("ix_shadow_router_record_conversation_id"), table_name="shadow_router_record"
    )
    op.drop_table("shadow_router_record")
    op.drop_table("knowledge_scope")
    op.drop_table("document_strategy")
    op.drop_table("conversation_session")
    op.drop_table("conversation_memory")
    op.drop_table("admin_user")
    # ### end Alembic commands ###
