"""add_conversation_trace_stage

Revision ID: c38283c3e66b
Revises: 03ee6f4c98b0
Create Date: 2026-05-23 21:35:39.077298

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c38283c3e66b"
down_revision: str | None = "03ee6f4c98b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_trace_stage",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("conversation_id", sa.String(length=64), nullable=False),
        sa.Column("exchange_id", sa.BigInteger(), nullable=False),
        sa.Column("stage_code", sa.String(length=64), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("stage_desc", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error_msg", sa.Text(), nullable=True),
        sa.Column("metrics_json", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversation_trace_stage_conversation_id"),
        "conversation_trace_stage",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_trace_stage_exchange_id"),
        "conversation_trace_stage",
        ["exchange_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_conversation_trace_stage_exchange_id"), table_name="conversation_trace_stage"
    )
    op.drop_index(
        op.f("ix_conversation_trace_stage_conversation_id"), table_name="conversation_trace_stage"
    )
    op.drop_table("conversation_trace_stage")
    # ### end Alembic commands ###
